/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./nexus/context"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Json";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Json custom scalar type
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Json";
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  EnumsaleTypeFieldUpdateOperationsInput: { // input type
    set?: NexusGenEnums['saleType'] | null; // saleType
  }
  EnumsaleTypeFilter: { // input type
    equals?: NexusGenEnums['saleType'] | null; // saleType
    in?: Array<NexusGenEnums['saleType'] | null> | null; // [saleType]
    not?: NexusGenInputs['NestedEnumsaleTypeFilter'] | null; // NestedEnumsaleTypeFilter
    notIn?: Array<NexusGenEnums['saleType'] | null> | null; // [saleType]
  }
  FloatFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Float
    divide?: number | null; // Float
    increment?: number | null; // Float
    multiply?: number | null; // Float
    set?: number | null; // Float
  }
  FloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: Array<number | null> | null; // [Float]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  ItemCreateInput: { // input type
    category: string; // String!
    description: string; // String!
    id?: string | null; // String
    name: string; // String!
    OrderItems?: NexusGenInputs['OrderItemCreateManyWithoutItemInput'] | null; // OrderItemCreateManyWithoutItemInput
    saleType: NexusGenEnums['saleType']; // saleType!
    snHerzelia?: string | null; // String
    snWebSite?: string | null; // String
  }
  ItemCreateOneWithoutOrderItemsInput: { // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ItemCreateOrConnectWithoutOrderItemsInput'] | null; // ItemCreateOrConnectWithoutOrderItemsInput
    create?: NexusGenInputs['ItemCreateWithoutOrderItemsInput'] | null; // ItemCreateWithoutOrderItemsInput
  }
  ItemCreateOrConnectWithoutOrderItemsInput: { // input type
    create: NexusGenInputs['ItemCreateWithoutOrderItemsInput']; // ItemCreateWithoutOrderItemsInput!
    where: NexusGenInputs['ItemWhereUniqueInput']; // ItemWhereUniqueInput!
  }
  ItemCreateWithoutOrderItemsInput: { // input type
    category: string; // String!
    description: string; // String!
    id?: string | null; // String
    name: string; // String!
    saleType: NexusGenEnums['saleType']; // saleType!
    snHerzelia?: string | null; // String
    snWebSite?: string | null; // String
  }
  ItemOrderByInput: { // input type
    category?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    saleType?: NexusGenEnums['SortOrder'] | null; // SortOrder
    snHerzelia?: NexusGenEnums['SortOrder'] | null; // SortOrder
    snWebSite?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ItemRelationFilter: { // input type
    is?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    isNot?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
  }
  ItemUpdateInput: { // input type
    category?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    OrderItems?: NexusGenInputs['OrderItemUpdateManyWithoutItemInput'] | null; // OrderItemUpdateManyWithoutItemInput
    saleType?: NexusGenInputs['EnumsaleTypeFieldUpdateOperationsInput'] | null; // EnumsaleTypeFieldUpdateOperationsInput
    snHerzelia?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    snWebSite?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  ItemUpdateManyMutationInput: { // input type
    category?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    saleType?: NexusGenInputs['EnumsaleTypeFieldUpdateOperationsInput'] | null; // EnumsaleTypeFieldUpdateOperationsInput
    snHerzelia?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    snWebSite?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  ItemUpdateOneRequiredWithoutOrderItemsInput: { // input type
    connect?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ItemCreateOrConnectWithoutOrderItemsInput'] | null; // ItemCreateOrConnectWithoutOrderItemsInput
    create?: NexusGenInputs['ItemCreateWithoutOrderItemsInput'] | null; // ItemCreateWithoutOrderItemsInput
    update?: NexusGenInputs['ItemUpdateWithoutOrderItemsInput'] | null; // ItemUpdateWithoutOrderItemsInput
    upsert?: NexusGenInputs['ItemUpsertWithoutOrderItemsInput'] | null; // ItemUpsertWithoutOrderItemsInput
  }
  ItemUpdateWithoutOrderItemsInput: { // input type
    category?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    saleType?: NexusGenInputs['EnumsaleTypeFieldUpdateOperationsInput'] | null; // EnumsaleTypeFieldUpdateOperationsInput
    snHerzelia?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    snWebSite?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  ItemUpsertWithoutOrderItemsInput: { // input type
    create: NexusGenInputs['ItemCreateWithoutOrderItemsInput']; // ItemCreateWithoutOrderItemsInput!
    update: NexusGenInputs['ItemUpdateWithoutOrderItemsInput']; // ItemUpdateWithoutOrderItemsInput!
  }
  ItemWhereInput: { // input type
    AND?: Array<NexusGenInputs['ItemWhereInput'] | null> | null; // [ItemWhereInput]
    category?: NexusGenInputs['StringFilter'] | null; // StringFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: Array<NexusGenInputs['ItemWhereInput'] | null> | null; // [ItemWhereInput]
    OR?: Array<NexusGenInputs['ItemWhereInput'] | null> | null; // [ItemWhereInput]
    OrderItems?: NexusGenInputs['OrderItemListRelationFilter'] | null; // OrderItemListRelationFilter
    saleType?: NexusGenInputs['EnumsaleTypeFilter'] | null; // EnumsaleTypeFilter
    snHerzelia?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    snWebSite?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  ItemWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: Array<NexusGenScalars['DateTime'] | null> | null; // [DateTime]
  }
  NestedEnumsaleTypeFilter: { // input type
    equals?: NexusGenEnums['saleType'] | null; // saleType
    in?: Array<NexusGenEnums['saleType'] | null> | null; // [saleType]
    not?: NexusGenInputs['NestedEnumsaleTypeFilter'] | null; // NestedEnumsaleTypeFilter
    notIn?: Array<NexusGenEnums['saleType'] | null> | null; // [saleType]
  }
  NestedFloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: Array<number | null> | null; // [Float]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: Array<number | null> | null; // [Float]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: Array<number | null> | null; // [Int]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: Array<number | null> | null; // [Int]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  OrderCreateInput: { // input type
    date: NexusGenScalars['DateTime']; // DateTime!
    items?: NexusGenInputs['OrderItemCreateManyWithoutOrderInput'] | null; // OrderItemCreateManyWithoutOrderInput
    supplier: NexusGenInputs['SupplierCreateOneWithoutOrderInput']; // SupplierCreateOneWithoutOrderInput!
  }
  OrderCreateManyWithoutSupplierInput: { // input type
    connect?: Array<NexusGenInputs['OrderWhereUniqueInput'] | null> | null; // [OrderWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderCreateOrConnectWithoutsupplierInput'] | null> | null; // [OrderCreateOrConnectWithoutsupplierInput]
    create?: Array<NexusGenInputs['OrderCreateWithoutSupplierInput'] | null> | null; // [OrderCreateWithoutSupplierInput]
  }
  OrderCreateOneWithoutItemsInput: { // input type
    connect?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
    connectOrCreate?: NexusGenInputs['OrderCreateOrConnectWithoutitemsInput'] | null; // OrderCreateOrConnectWithoutitemsInput
    create?: NexusGenInputs['OrderCreateWithoutItemsInput'] | null; // OrderCreateWithoutItemsInput
  }
  OrderCreateOrConnectWithoutitemsInput: { // input type
    create: NexusGenInputs['OrderCreateWithoutItemsInput']; // OrderCreateWithoutItemsInput!
    where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
  }
  OrderCreateOrConnectWithoutsupplierInput: { // input type
    create: NexusGenInputs['OrderCreateWithoutSupplierInput']; // OrderCreateWithoutSupplierInput!
    where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
  }
  OrderCreateWithoutItemsInput: { // input type
    date: NexusGenScalars['DateTime']; // DateTime!
    supplier: NexusGenInputs['SupplierCreateOneWithoutOrderInput']; // SupplierCreateOneWithoutOrderInput!
  }
  OrderCreateWithoutSupplierInput: { // input type
    date: NexusGenScalars['DateTime']; // DateTime!
    items?: NexusGenInputs['OrderItemCreateManyWithoutOrderInput'] | null; // OrderItemCreateManyWithoutOrderInput
  }
  OrderItemCreateInput: { // input type
    item: NexusGenInputs['ItemCreateOneWithoutOrderItemsInput']; // ItemCreateOneWithoutOrderItemsInput!
    Order: NexusGenInputs['OrderCreateOneWithoutItemsInput']; // OrderCreateOneWithoutItemsInput!
    quantity: number; // Float!
    receiptNumber: string; // String!
    supplier: NexusGenInputs['SupplierCreateOneWithoutOrderItemInput']; // SupplierCreateOneWithoutOrderItemInput!
  }
  OrderItemCreateManyWithoutItemInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutitemInput'] | null> | null; // [OrderItemCreateOrConnectWithoutitemInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutItemInput'] | null> | null; // [OrderItemCreateWithoutItemInput]
  }
  OrderItemCreateManyWithoutOrderInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutOrderInput'] | null> | null; // [OrderItemCreateOrConnectWithoutOrderInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutOrderInput'] | null> | null; // [OrderItemCreateWithoutOrderInput]
  }
  OrderItemCreateManyWithoutSupplierInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutsupplierInput'] | null> | null; // [OrderItemCreateOrConnectWithoutsupplierInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutSupplierInput'] | null> | null; // [OrderItemCreateWithoutSupplierInput]
  }
  OrderItemCreateOrConnectWithoutOrderInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutOrderInput']; // OrderItemCreateWithoutOrderInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemCreateOrConnectWithoutitemInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutItemInput']; // OrderItemCreateWithoutItemInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemCreateOrConnectWithoutsupplierInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutSupplierInput']; // OrderItemCreateWithoutSupplierInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemCreateWithoutItemInput: { // input type
    Order: NexusGenInputs['OrderCreateOneWithoutItemsInput']; // OrderCreateOneWithoutItemsInput!
    quantity: number; // Float!
    receiptNumber: string; // String!
    supplier: NexusGenInputs['SupplierCreateOneWithoutOrderItemInput']; // SupplierCreateOneWithoutOrderItemInput!
  }
  OrderItemCreateWithoutOrderInput: { // input type
    item: NexusGenInputs['ItemCreateOneWithoutOrderItemsInput']; // ItemCreateOneWithoutOrderItemsInput!
    quantity: number; // Float!
    receiptNumber: string; // String!
    supplier: NexusGenInputs['SupplierCreateOneWithoutOrderItemInput']; // SupplierCreateOneWithoutOrderItemInput!
  }
  OrderItemCreateWithoutSupplierInput: { // input type
    item: NexusGenInputs['ItemCreateOneWithoutOrderItemsInput']; // ItemCreateOneWithoutOrderItemsInput!
    Order: NexusGenInputs['OrderCreateOneWithoutItemsInput']; // OrderCreateOneWithoutItemsInput!
    quantity: number; // Float!
    receiptNumber: string; // String!
  }
  OrderItemListRelationFilter: { // input type
    every?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    none?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    some?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
  }
  OrderItemOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    itemId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    orderId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    quantity?: NexusGenEnums['SortOrder'] | null; // SortOrder
    receiptNumber?: NexusGenEnums['SortOrder'] | null; // SortOrder
    supplierId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  OrderItemScalarWhereInput: { // input type
    AND?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    itemId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    OR?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    orderId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    quantity?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    receiptNumber?: NexusGenInputs['StringFilter'] | null; // StringFilter
    supplierId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  OrderItemUpdateInput: { // input type
    item?: NexusGenInputs['ItemUpdateOneRequiredWithoutOrderItemsInput'] | null; // ItemUpdateOneRequiredWithoutOrderItemsInput
    Order?: NexusGenInputs['OrderUpdateOneRequiredWithoutItemsInput'] | null; // OrderUpdateOneRequiredWithoutItemsInput
    quantity?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    receiptNumber?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    supplier?: NexusGenInputs['SupplierUpdateOneRequiredWithoutOrderItemInput'] | null; // SupplierUpdateOneRequiredWithoutOrderItemInput
  }
  OrderItemUpdateManyMutationInput: { // input type
    quantity?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    receiptNumber?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  OrderItemUpdateManyWithWhereWithoutItemInput: { // input type
    data: NexusGenInputs['OrderItemUpdateManyMutationInput']; // OrderItemUpdateManyMutationInput!
    where: NexusGenInputs['OrderItemScalarWhereInput']; // OrderItemScalarWhereInput!
  }
  OrderItemUpdateManyWithWhereWithoutOrderInput: { // input type
    data: NexusGenInputs['OrderItemUpdateManyMutationInput']; // OrderItemUpdateManyMutationInput!
    where: NexusGenInputs['OrderItemScalarWhereInput']; // OrderItemScalarWhereInput!
  }
  OrderItemUpdateManyWithWhereWithoutSupplierInput: { // input type
    data: NexusGenInputs['OrderItemUpdateManyMutationInput']; // OrderItemUpdateManyMutationInput!
    where: NexusGenInputs['OrderItemScalarWhereInput']; // OrderItemScalarWhereInput!
  }
  OrderItemUpdateManyWithoutItemInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutitemInput'] | null> | null; // [OrderItemCreateOrConnectWithoutitemInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutItemInput'] | null> | null; // [OrderItemCreateWithoutItemInput]
    delete?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    disconnect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    set?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    update?: Array<NexusGenInputs['OrderItemUpdateWithWhereUniqueWithoutItemInput'] | null> | null; // [OrderItemUpdateWithWhereUniqueWithoutItemInput]
    updateMany?: Array<NexusGenInputs['OrderItemUpdateManyWithWhereWithoutItemInput'] | null> | null; // [OrderItemUpdateManyWithWhereWithoutItemInput]
    upsert?: Array<NexusGenInputs['OrderItemUpsertWithWhereUniqueWithoutItemInput'] | null> | null; // [OrderItemUpsertWithWhereUniqueWithoutItemInput]
  }
  OrderItemUpdateManyWithoutOrderInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutOrderInput'] | null> | null; // [OrderItemCreateOrConnectWithoutOrderInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutOrderInput'] | null> | null; // [OrderItemCreateWithoutOrderInput]
    delete?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    disconnect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    set?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    update?: Array<NexusGenInputs['OrderItemUpdateWithWhereUniqueWithoutOrderInput'] | null> | null; // [OrderItemUpdateWithWhereUniqueWithoutOrderInput]
    updateMany?: Array<NexusGenInputs['OrderItemUpdateManyWithWhereWithoutOrderInput'] | null> | null; // [OrderItemUpdateManyWithWhereWithoutOrderInput]
    upsert?: Array<NexusGenInputs['OrderItemUpsertWithWhereUniqueWithoutOrderInput'] | null> | null; // [OrderItemUpsertWithWhereUniqueWithoutOrderInput]
  }
  OrderItemUpdateManyWithoutSupplierInput: { // input type
    connect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderItemCreateOrConnectWithoutsupplierInput'] | null> | null; // [OrderItemCreateOrConnectWithoutsupplierInput]
    create?: Array<NexusGenInputs['OrderItemCreateWithoutSupplierInput'] | null> | null; // [OrderItemCreateWithoutSupplierInput]
    delete?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['OrderItemScalarWhereInput'] | null> | null; // [OrderItemScalarWhereInput]
    disconnect?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    set?: Array<NexusGenInputs['OrderItemWhereUniqueInput'] | null> | null; // [OrderItemWhereUniqueInput]
    update?: Array<NexusGenInputs['OrderItemUpdateWithWhereUniqueWithoutSupplierInput'] | null> | null; // [OrderItemUpdateWithWhereUniqueWithoutSupplierInput]
    updateMany?: Array<NexusGenInputs['OrderItemUpdateManyWithWhereWithoutSupplierInput'] | null> | null; // [OrderItemUpdateManyWithWhereWithoutSupplierInput]
    upsert?: Array<NexusGenInputs['OrderItemUpsertWithWhereUniqueWithoutSupplierInput'] | null> | null; // [OrderItemUpsertWithWhereUniqueWithoutSupplierInput]
  }
  OrderItemUpdateWithWhereUniqueWithoutItemInput: { // input type
    data: NexusGenInputs['OrderItemUpdateWithoutItemInput']; // OrderItemUpdateWithoutItemInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemUpdateWithWhereUniqueWithoutOrderInput: { // input type
    data: NexusGenInputs['OrderItemUpdateWithoutOrderInput']; // OrderItemUpdateWithoutOrderInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemUpdateWithWhereUniqueWithoutSupplierInput: { // input type
    data: NexusGenInputs['OrderItemUpdateWithoutSupplierInput']; // OrderItemUpdateWithoutSupplierInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemUpdateWithoutItemInput: { // input type
    Order?: NexusGenInputs['OrderUpdateOneRequiredWithoutItemsInput'] | null; // OrderUpdateOneRequiredWithoutItemsInput
    quantity?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    receiptNumber?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    supplier?: NexusGenInputs['SupplierUpdateOneRequiredWithoutOrderItemInput'] | null; // SupplierUpdateOneRequiredWithoutOrderItemInput
  }
  OrderItemUpdateWithoutOrderInput: { // input type
    item?: NexusGenInputs['ItemUpdateOneRequiredWithoutOrderItemsInput'] | null; // ItemUpdateOneRequiredWithoutOrderItemsInput
    quantity?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    receiptNumber?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    supplier?: NexusGenInputs['SupplierUpdateOneRequiredWithoutOrderItemInput'] | null; // SupplierUpdateOneRequiredWithoutOrderItemInput
  }
  OrderItemUpdateWithoutSupplierInput: { // input type
    item?: NexusGenInputs['ItemUpdateOneRequiredWithoutOrderItemsInput'] | null; // ItemUpdateOneRequiredWithoutOrderItemsInput
    Order?: NexusGenInputs['OrderUpdateOneRequiredWithoutItemsInput'] | null; // OrderUpdateOneRequiredWithoutItemsInput
    quantity?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    receiptNumber?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  OrderItemUpsertWithWhereUniqueWithoutItemInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutItemInput']; // OrderItemCreateWithoutItemInput!
    update: NexusGenInputs['OrderItemUpdateWithoutItemInput']; // OrderItemUpdateWithoutItemInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemUpsertWithWhereUniqueWithoutOrderInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutOrderInput']; // OrderItemCreateWithoutOrderInput!
    update: NexusGenInputs['OrderItemUpdateWithoutOrderInput']; // OrderItemUpdateWithoutOrderInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemUpsertWithWhereUniqueWithoutSupplierInput: { // input type
    create: NexusGenInputs['OrderItemCreateWithoutSupplierInput']; // OrderItemCreateWithoutSupplierInput!
    update: NexusGenInputs['OrderItemUpdateWithoutSupplierInput']; // OrderItemUpdateWithoutSupplierInput!
    where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
  }
  OrderItemWhereInput: { // input type
    AND?: Array<NexusGenInputs['OrderItemWhereInput'] | null> | null; // [OrderItemWhereInput]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    item?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    itemId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: Array<NexusGenInputs['OrderItemWhereInput'] | null> | null; // [OrderItemWhereInput]
    OR?: Array<NexusGenInputs['OrderItemWhereInput'] | null> | null; // [OrderItemWhereInput]
    Order?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    orderId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    quantity?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    receiptNumber?: NexusGenInputs['StringFilter'] | null; // StringFilter
    supplier?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    supplierId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  OrderItemWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  OrderListRelationFilter: { // input type
    every?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    none?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    some?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
  }
  OrderOrderByInput: { // input type
    date?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    supplierId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  OrderRelationFilter: { // input type
    is?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    isNot?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
  }
  OrderScalarWhereInput: { // input type
    AND?: Array<NexusGenInputs['OrderScalarWhereInput'] | null> | null; // [OrderScalarWhereInput]
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: Array<NexusGenInputs['OrderScalarWhereInput'] | null> | null; // [OrderScalarWhereInput]
    OR?: Array<NexusGenInputs['OrderScalarWhereInput'] | null> | null; // [OrderScalarWhereInput]
    supplierId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  OrderUpdateInput: { // input type
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    items?: NexusGenInputs['OrderItemUpdateManyWithoutOrderInput'] | null; // OrderItemUpdateManyWithoutOrderInput
    supplier?: NexusGenInputs['SupplierUpdateOneRequiredWithoutOrderInput'] | null; // SupplierUpdateOneRequiredWithoutOrderInput
  }
  OrderUpdateManyMutationInput: { // input type
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  OrderUpdateManyWithWhereWithoutSupplierInput: { // input type
    data: NexusGenInputs['OrderUpdateManyMutationInput']; // OrderUpdateManyMutationInput!
    where: NexusGenInputs['OrderScalarWhereInput']; // OrderScalarWhereInput!
  }
  OrderUpdateManyWithoutSupplierInput: { // input type
    connect?: Array<NexusGenInputs['OrderWhereUniqueInput'] | null> | null; // [OrderWhereUniqueInput]
    connectOrCreate?: Array<NexusGenInputs['OrderCreateOrConnectWithoutsupplierInput'] | null> | null; // [OrderCreateOrConnectWithoutsupplierInput]
    create?: Array<NexusGenInputs['OrderCreateWithoutSupplierInput'] | null> | null; // [OrderCreateWithoutSupplierInput]
    delete?: Array<NexusGenInputs['OrderWhereUniqueInput'] | null> | null; // [OrderWhereUniqueInput]
    deleteMany?: Array<NexusGenInputs['OrderScalarWhereInput'] | null> | null; // [OrderScalarWhereInput]
    disconnect?: Array<NexusGenInputs['OrderWhereUniqueInput'] | null> | null; // [OrderWhereUniqueInput]
    set?: Array<NexusGenInputs['OrderWhereUniqueInput'] | null> | null; // [OrderWhereUniqueInput]
    update?: Array<NexusGenInputs['OrderUpdateWithWhereUniqueWithoutSupplierInput'] | null> | null; // [OrderUpdateWithWhereUniqueWithoutSupplierInput]
    updateMany?: Array<NexusGenInputs['OrderUpdateManyWithWhereWithoutSupplierInput'] | null> | null; // [OrderUpdateManyWithWhereWithoutSupplierInput]
    upsert?: Array<NexusGenInputs['OrderUpsertWithWhereUniqueWithoutSupplierInput'] | null> | null; // [OrderUpsertWithWhereUniqueWithoutSupplierInput]
  }
  OrderUpdateOneRequiredWithoutItemsInput: { // input type
    connect?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
    connectOrCreate?: NexusGenInputs['OrderCreateOrConnectWithoutitemsInput'] | null; // OrderCreateOrConnectWithoutitemsInput
    create?: NexusGenInputs['OrderCreateWithoutItemsInput'] | null; // OrderCreateWithoutItemsInput
    update?: NexusGenInputs['OrderUpdateWithoutItemsInput'] | null; // OrderUpdateWithoutItemsInput
    upsert?: NexusGenInputs['OrderUpsertWithoutItemsInput'] | null; // OrderUpsertWithoutItemsInput
  }
  OrderUpdateWithWhereUniqueWithoutSupplierInput: { // input type
    data: NexusGenInputs['OrderUpdateWithoutSupplierInput']; // OrderUpdateWithoutSupplierInput!
    where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
  }
  OrderUpdateWithoutItemsInput: { // input type
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    supplier?: NexusGenInputs['SupplierUpdateOneRequiredWithoutOrderInput'] | null; // SupplierUpdateOneRequiredWithoutOrderInput
  }
  OrderUpdateWithoutSupplierInput: { // input type
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    items?: NexusGenInputs['OrderItemUpdateManyWithoutOrderInput'] | null; // OrderItemUpdateManyWithoutOrderInput
  }
  OrderUpsertWithWhereUniqueWithoutSupplierInput: { // input type
    create: NexusGenInputs['OrderCreateWithoutSupplierInput']; // OrderCreateWithoutSupplierInput!
    update: NexusGenInputs['OrderUpdateWithoutSupplierInput']; // OrderUpdateWithoutSupplierInput!
    where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
  }
  OrderUpsertWithoutItemsInput: { // input type
    create: NexusGenInputs['OrderCreateWithoutItemsInput']; // OrderCreateWithoutItemsInput!
    update: NexusGenInputs['OrderUpdateWithoutItemsInput']; // OrderUpdateWithoutItemsInput!
  }
  OrderWhereInput: { // input type
    AND?: Array<NexusGenInputs['OrderWhereInput'] | null> | null; // [OrderWhereInput]
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    items?: NexusGenInputs['OrderItemListRelationFilter'] | null; // OrderItemListRelationFilter
    NOT?: Array<NexusGenInputs['OrderWhereInput'] | null> | null; // [OrderWhereInput]
    OR?: Array<NexusGenInputs['OrderWhereInput'] | null> | null; // [OrderWhereInput]
    supplier?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    supplierId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  OrderWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: Array<string | null> | null; // [String]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: Array<string | null> | null; // [String]
    startsWith?: string | null; // String
  }
  SupplierCreateInput: { // input type
    name: string; // String!
    Order?: NexusGenInputs['OrderCreateManyWithoutSupplierInput'] | null; // OrderCreateManyWithoutSupplierInput
    OrderItem?: NexusGenInputs['OrderItemCreateManyWithoutSupplierInput'] | null; // OrderItemCreateManyWithoutSupplierInput
  }
  SupplierCreateOneWithoutOrderInput: { // input type
    connect?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SupplierCreateOrConnectWithoutOrderInput'] | null; // SupplierCreateOrConnectWithoutOrderInput
    create?: NexusGenInputs['SupplierCreateWithoutOrderInput'] | null; // SupplierCreateWithoutOrderInput
  }
  SupplierCreateOneWithoutOrderItemInput: { // input type
    connect?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SupplierCreateOrConnectWithoutOrderItemInput'] | null; // SupplierCreateOrConnectWithoutOrderItemInput
    create?: NexusGenInputs['SupplierCreateWithoutOrderItemInput'] | null; // SupplierCreateWithoutOrderItemInput
  }
  SupplierCreateOrConnectWithoutOrderInput: { // input type
    create: NexusGenInputs['SupplierCreateWithoutOrderInput']; // SupplierCreateWithoutOrderInput!
    where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
  }
  SupplierCreateOrConnectWithoutOrderItemInput: { // input type
    create: NexusGenInputs['SupplierCreateWithoutOrderItemInput']; // SupplierCreateWithoutOrderItemInput!
    where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
  }
  SupplierCreateWithoutOrderInput: { // input type
    name: string; // String!
    OrderItem?: NexusGenInputs['OrderItemCreateManyWithoutSupplierInput'] | null; // OrderItemCreateManyWithoutSupplierInput
  }
  SupplierCreateWithoutOrderItemInput: { // input type
    name: string; // String!
    Order?: NexusGenInputs['OrderCreateManyWithoutSupplierInput'] | null; // OrderCreateManyWithoutSupplierInput
  }
  SupplierOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SupplierRelationFilter: { // input type
    is?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    isNot?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
  }
  SupplierUpdateInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Order?: NexusGenInputs['OrderUpdateManyWithoutSupplierInput'] | null; // OrderUpdateManyWithoutSupplierInput
    OrderItem?: NexusGenInputs['OrderItemUpdateManyWithoutSupplierInput'] | null; // OrderItemUpdateManyWithoutSupplierInput
  }
  SupplierUpdateManyMutationInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  SupplierUpdateOneRequiredWithoutOrderInput: { // input type
    connect?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SupplierCreateOrConnectWithoutOrderInput'] | null; // SupplierCreateOrConnectWithoutOrderInput
    create?: NexusGenInputs['SupplierCreateWithoutOrderInput'] | null; // SupplierCreateWithoutOrderInput
    update?: NexusGenInputs['SupplierUpdateWithoutOrderInput'] | null; // SupplierUpdateWithoutOrderInput
    upsert?: NexusGenInputs['SupplierUpsertWithoutOrderInput'] | null; // SupplierUpsertWithoutOrderInput
  }
  SupplierUpdateOneRequiredWithoutOrderItemInput: { // input type
    connect?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SupplierCreateOrConnectWithoutOrderItemInput'] | null; // SupplierCreateOrConnectWithoutOrderItemInput
    create?: NexusGenInputs['SupplierCreateWithoutOrderItemInput'] | null; // SupplierCreateWithoutOrderItemInput
    update?: NexusGenInputs['SupplierUpdateWithoutOrderItemInput'] | null; // SupplierUpdateWithoutOrderItemInput
    upsert?: NexusGenInputs['SupplierUpsertWithoutOrderItemInput'] | null; // SupplierUpsertWithoutOrderItemInput
  }
  SupplierUpdateWithoutOrderInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    OrderItem?: NexusGenInputs['OrderItemUpdateManyWithoutSupplierInput'] | null; // OrderItemUpdateManyWithoutSupplierInput
  }
  SupplierUpdateWithoutOrderItemInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    Order?: NexusGenInputs['OrderUpdateManyWithoutSupplierInput'] | null; // OrderUpdateManyWithoutSupplierInput
  }
  SupplierUpsertWithoutOrderInput: { // input type
    create: NexusGenInputs['SupplierCreateWithoutOrderInput']; // SupplierCreateWithoutOrderInput!
    update: NexusGenInputs['SupplierUpdateWithoutOrderInput']; // SupplierUpdateWithoutOrderInput!
  }
  SupplierUpsertWithoutOrderItemInput: { // input type
    create: NexusGenInputs['SupplierCreateWithoutOrderItemInput']; // SupplierCreateWithoutOrderItemInput!
    update: NexusGenInputs['SupplierUpdateWithoutOrderItemInput']; // SupplierUpdateWithoutOrderItemInput!
  }
  SupplierWhereInput: { // input type
    AND?: Array<NexusGenInputs['SupplierWhereInput'] | null> | null; // [SupplierWhereInput]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: Array<NexusGenInputs['SupplierWhereInput'] | null> | null; // [SupplierWhereInput]
    OR?: Array<NexusGenInputs['SupplierWhereInput'] | null> | null; // [SupplierWhereInput]
    Order?: NexusGenInputs['OrderListRelationFilter'] | null; // OrderListRelationFilter
    OrderItem?: NexusGenInputs['OrderItemListRelationFilter'] | null; // OrderItemListRelationFilter
  }
  SupplierWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  UserCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserWhereInput: { // input type
    AND?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    OR?: Array<NexusGenInputs['UserWhereInput'] | null> | null; // [UserWhereInput]
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  ItemScalarFieldEnum: "category" | "description" | "id" | "name" | "saleType" | "snHerzelia" | "snWebSite"
  OrderItemScalarFieldEnum: "id" | "itemId" | "orderId" | "quantity" | "receiptNumber" | "supplierId"
  OrderScalarFieldEnum: "date" | "id" | "supplierId"
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
  SupplierScalarFieldEnum: "id" | "name"
  UserScalarFieldEnum: "createdAt" | "email" | "id" | "name" | "updatedAt"
  saleType: "KG" | "PACK" | "UNIT" | "WIEGHT_PACK"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Json: any
}

export interface NexusGenObjects {
  AggregateItem: { // root type
    count?: NexusGenRootTypes['ItemCountAggregateOutputType'] | null; // ItemCountAggregateOutputType
    max?: NexusGenRootTypes['ItemMaxAggregateOutputType'] | null; // ItemMaxAggregateOutputType
    min?: NexusGenRootTypes['ItemMinAggregateOutputType'] | null; // ItemMinAggregateOutputType
  }
  AggregateOrder: { // root type
    avg?: NexusGenRootTypes['OrderAvgAggregateOutputType'] | null; // OrderAvgAggregateOutputType
    count?: NexusGenRootTypes['OrderCountAggregateOutputType'] | null; // OrderCountAggregateOutputType
    max?: NexusGenRootTypes['OrderMaxAggregateOutputType'] | null; // OrderMaxAggregateOutputType
    min?: NexusGenRootTypes['OrderMinAggregateOutputType'] | null; // OrderMinAggregateOutputType
    sum?: NexusGenRootTypes['OrderSumAggregateOutputType'] | null; // OrderSumAggregateOutputType
  }
  AggregateOrderItem: { // root type
    avg?: NexusGenRootTypes['OrderItemAvgAggregateOutputType'] | null; // OrderItemAvgAggregateOutputType
    count?: NexusGenRootTypes['OrderItemCountAggregateOutputType'] | null; // OrderItemCountAggregateOutputType
    max?: NexusGenRootTypes['OrderItemMaxAggregateOutputType'] | null; // OrderItemMaxAggregateOutputType
    min?: NexusGenRootTypes['OrderItemMinAggregateOutputType'] | null; // OrderItemMinAggregateOutputType
    sum?: NexusGenRootTypes['OrderItemSumAggregateOutputType'] | null; // OrderItemSumAggregateOutputType
  }
  AggregateSupplier: { // root type
    avg?: NexusGenRootTypes['SupplierAvgAggregateOutputType'] | null; // SupplierAvgAggregateOutputType
    count?: NexusGenRootTypes['SupplierCountAggregateOutputType'] | null; // SupplierCountAggregateOutputType
    max?: NexusGenRootTypes['SupplierMaxAggregateOutputType'] | null; // SupplierMaxAggregateOutputType
    min?: NexusGenRootTypes['SupplierMinAggregateOutputType'] | null; // SupplierMinAggregateOutputType
    sum?: NexusGenRootTypes['SupplierSumAggregateOutputType'] | null; // SupplierSumAggregateOutputType
  }
  AggregateUser: { // root type
    avg?: NexusGenRootTypes['UserAvgAggregateOutputType'] | null; // UserAvgAggregateOutputType
    count?: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max?: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min?: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
    sum?: NexusGenRootTypes['UserSumAggregateOutputType'] | null; // UserSumAggregateOutputType
  }
  BatchPayload: { // root type
    count: number; // Int!
  }
  Item: { // root type
    category: string; // String!
    description: string; // String!
    id: string; // String!
    name: string; // String!
    saleType: NexusGenEnums['saleType']; // saleType!
    snHerzelia?: string | null; // String
    snWebSite?: string | null; // String
  }
  ItemCountAggregateOutputType: { // root type
    _all: number; // Int!
    category?: number | null; // Int
    description?: number | null; // Int
    id?: number | null; // Int
    name?: number | null; // Int
    saleType?: number | null; // Int
    snHerzelia?: number | null; // Int
    snWebSite?: number | null; // Int
  }
  ItemMaxAggregateOutputType: { // root type
    category?: string | null; // String
    description?: string | null; // String
    id?: string | null; // String
    name?: string | null; // String
    saleType?: NexusGenEnums['saleType'] | null; // saleType
    snHerzelia?: string | null; // String
    snWebSite?: string | null; // String
  }
  ItemMinAggregateOutputType: { // root type
    category?: string | null; // String
    description?: string | null; // String
    id?: string | null; // String
    name?: string | null; // String
    saleType?: NexusGenEnums['saleType'] | null; // saleType
    snHerzelia?: string | null; // String
    snWebSite?: string | null; // String
  }
  Mutation: {};
  Order: { // root type
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderAvgAggregateOutputType: { // root type
    id: number; // Float!
    supplierId: number; // Float!
  }
  OrderCountAggregateOutputType: { // root type
    _all: number; // Int!
    date?: number | null; // Int
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderItem: { // root type
    id: number; // Int!
    itemId: string; // String!
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber: string; // String!
    supplierId: number; // Int!
  }
  OrderItemAvgAggregateOutputType: { // root type
    id: number; // Float!
    orderId: number; // Float!
    quantity: number; // Float!
    supplierId: number; // Float!
  }
  OrderItemCountAggregateOutputType: { // root type
    _all: number; // Int!
    id: number; // Int!
    itemId?: number | null; // Int
    orderId: number; // Int!
    quantity: number; // Int!
    receiptNumber?: number | null; // Int
    supplierId: number; // Int!
  }
  OrderItemMaxAggregateOutputType: { // root type
    id: number; // Int!
    itemId?: string | null; // String
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber?: string | null; // String
    supplierId: number; // Int!
  }
  OrderItemMinAggregateOutputType: { // root type
    id: number; // Int!
    itemId?: string | null; // String
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber?: string | null; // String
    supplierId: number; // Int!
  }
  OrderItemSumAggregateOutputType: { // root type
    id: number; // Int!
    orderId: number; // Int!
    quantity: number; // Float!
    supplierId: number; // Int!
  }
  OrderMaxAggregateOutputType: { // root type
    date?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderMinAggregateOutputType: { // root type
    date?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderSumAggregateOutputType: { // root type
    id: number; // Int!
    supplierId: number; // Int!
  }
  Query: {};
  Supplier: { // root type
    id: number; // Int!
    name: string; // String!
  }
  SupplierAvgAggregateOutputType: { // root type
    id: number; // Float!
  }
  SupplierCountAggregateOutputType: { // root type
    _all: number; // Int!
    id: number; // Int!
    name?: number | null; // Int
  }
  SupplierMaxAggregateOutputType: { // root type
    id: number; // Int!
    name?: string | null; // String
  }
  SupplierMinAggregateOutputType: { // root type
    id: number; // Int!
    name?: string | null; // String
  }
  SupplierSumAggregateOutputType: { // root type
    id: number; // Int!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email?: string | null; // String
    id: number; // Int!
    name?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserAvgAggregateOutputType: { // root type
    id: number; // Float!
  }
  UserCountAggregateOutputType: { // root type
    _all: number; // Int!
    createdAt?: number | null; // Int
    email?: number | null; // Int
    id: number; // Int!
    name?: number | null; // Int
    updatedAt?: number | null; // Int
  }
  UserMaxAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    id: number; // Int!
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserMinAggregateOutputType: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    id: number; // Int!
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserSumAggregateOutputType: { // root type
    id: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AggregateItem: { // field return type
    count: NexusGenRootTypes['ItemCountAggregateOutputType'] | null; // ItemCountAggregateOutputType
    max: NexusGenRootTypes['ItemMaxAggregateOutputType'] | null; // ItemMaxAggregateOutputType
    min: NexusGenRootTypes['ItemMinAggregateOutputType'] | null; // ItemMinAggregateOutputType
  }
  AggregateOrder: { // field return type
    avg: NexusGenRootTypes['OrderAvgAggregateOutputType'] | null; // OrderAvgAggregateOutputType
    count: NexusGenRootTypes['OrderCountAggregateOutputType'] | null; // OrderCountAggregateOutputType
    max: NexusGenRootTypes['OrderMaxAggregateOutputType'] | null; // OrderMaxAggregateOutputType
    min: NexusGenRootTypes['OrderMinAggregateOutputType'] | null; // OrderMinAggregateOutputType
    sum: NexusGenRootTypes['OrderSumAggregateOutputType'] | null; // OrderSumAggregateOutputType
  }
  AggregateOrderItem: { // field return type
    avg: NexusGenRootTypes['OrderItemAvgAggregateOutputType'] | null; // OrderItemAvgAggregateOutputType
    count: NexusGenRootTypes['OrderItemCountAggregateOutputType'] | null; // OrderItemCountAggregateOutputType
    max: NexusGenRootTypes['OrderItemMaxAggregateOutputType'] | null; // OrderItemMaxAggregateOutputType
    min: NexusGenRootTypes['OrderItemMinAggregateOutputType'] | null; // OrderItemMinAggregateOutputType
    sum: NexusGenRootTypes['OrderItemSumAggregateOutputType'] | null; // OrderItemSumAggregateOutputType
  }
  AggregateSupplier: { // field return type
    avg: NexusGenRootTypes['SupplierAvgAggregateOutputType'] | null; // SupplierAvgAggregateOutputType
    count: NexusGenRootTypes['SupplierCountAggregateOutputType'] | null; // SupplierCountAggregateOutputType
    max: NexusGenRootTypes['SupplierMaxAggregateOutputType'] | null; // SupplierMaxAggregateOutputType
    min: NexusGenRootTypes['SupplierMinAggregateOutputType'] | null; // SupplierMinAggregateOutputType
    sum: NexusGenRootTypes['SupplierSumAggregateOutputType'] | null; // SupplierSumAggregateOutputType
  }
  AggregateUser: { // field return type
    avg: NexusGenRootTypes['UserAvgAggregateOutputType'] | null; // UserAvgAggregateOutputType
    count: NexusGenRootTypes['UserCountAggregateOutputType'] | null; // UserCountAggregateOutputType
    max: NexusGenRootTypes['UserMaxAggregateOutputType'] | null; // UserMaxAggregateOutputType
    min: NexusGenRootTypes['UserMinAggregateOutputType'] | null; // UserMinAggregateOutputType
    sum: NexusGenRootTypes['UserSumAggregateOutputType'] | null; // UserSumAggregateOutputType
  }
  BatchPayload: { // field return type
    count: number; // Int!
  }
  Item: { // field return type
    category: string; // String!
    description: string; // String!
    id: string; // String!
    name: string; // String!
    OrderItems: NexusGenRootTypes['OrderItem'][]; // [OrderItem!]!
    saleType: NexusGenEnums['saleType']; // saleType!
    snHerzelia: string | null; // String
    snWebSite: string | null; // String
  }
  ItemCountAggregateOutputType: { // field return type
    _all: number; // Int!
    category: number | null; // Int
    description: number | null; // Int
    id: number | null; // Int
    name: number | null; // Int
    saleType: number | null; // Int
    snHerzelia: number | null; // Int
    snWebSite: number | null; // Int
  }
  ItemMaxAggregateOutputType: { // field return type
    category: string | null; // String
    description: string | null; // String
    id: string | null; // String
    name: string | null; // String
    saleType: NexusGenEnums['saleType'] | null; // saleType
    snHerzelia: string | null; // String
    snWebSite: string | null; // String
  }
  ItemMinAggregateOutputType: { // field return type
    category: string | null; // String
    description: string | null; // String
    id: string | null; // String
    name: string | null; // String
    saleType: NexusGenEnums['saleType'] | null; // saleType
    snHerzelia: string | null; // String
    snWebSite: string | null; // String
  }
  Mutation: { // field return type
    createManyItem: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    createOneItem: NexusGenRootTypes['Item']; // Item!
    createOneOrder: NexusGenRootTypes['Order']; // Order!
    createOneOrderItem: NexusGenRootTypes['OrderItem']; // OrderItem!
    createOneSupplier: NexusGenRootTypes['Supplier']; // Supplier!
    createOneUser: NexusGenRootTypes['User']; // User!
    deleteManyItem: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteManyOrder: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteManyOrderItem: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteManySupplier: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteManyUser: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteOneItem: NexusGenRootTypes['Item'] | null; // Item
    deleteOneOrder: NexusGenRootTypes['Order'] | null; // Order
    deleteOneOrderItem: NexusGenRootTypes['OrderItem'] | null; // OrderItem
    deleteOneSupplier: NexusGenRootTypes['Supplier'] | null; // Supplier
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
    updateManyItem: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateManyOrder: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateManyOrderItem: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateManySupplier: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateManyUser: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateOneItem: NexusGenRootTypes['Item']; // Item!
    updateOneOrder: NexusGenRootTypes['Order']; // Order!
    updateOneOrderItem: NexusGenRootTypes['OrderItem']; // OrderItem!
    updateOneSupplier: NexusGenRootTypes['Supplier']; // Supplier!
    updateOneUser: NexusGenRootTypes['User']; // User!
    upsertOneItem: NexusGenRootTypes['Item']; // Item!
    upsertOneOrder: NexusGenRootTypes['Order']; // Order!
    upsertOneOrderItem: NexusGenRootTypes['OrderItem']; // OrderItem!
    upsertOneSupplier: NexusGenRootTypes['Supplier']; // Supplier!
    upsertOneUser: NexusGenRootTypes['User']; // User!
  }
  Order: { // field return type
    date: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    items: NexusGenRootTypes['OrderItem'][]; // [OrderItem!]!
    supplier: NexusGenRootTypes['Supplier']; // Supplier!
    supplierId: number; // Int!
  }
  OrderAvgAggregateOutputType: { // field return type
    id: number; // Float!
    supplierId: number; // Float!
  }
  OrderCountAggregateOutputType: { // field return type
    _all: number; // Int!
    date: number | null; // Int
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderItem: { // field return type
    id: number; // Int!
    item: NexusGenRootTypes['Item']; // Item!
    itemId: string; // String!
    Order: NexusGenRootTypes['Order']; // Order!
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber: string; // String!
    supplier: NexusGenRootTypes['Supplier']; // Supplier!
    supplierId: number; // Int!
  }
  OrderItemAvgAggregateOutputType: { // field return type
    id: number; // Float!
    orderId: number; // Float!
    quantity: number; // Float!
    supplierId: number; // Float!
  }
  OrderItemCountAggregateOutputType: { // field return type
    _all: number; // Int!
    id: number; // Int!
    itemId: number | null; // Int
    orderId: number; // Int!
    quantity: number; // Int!
    receiptNumber: number | null; // Int
    supplierId: number; // Int!
  }
  OrderItemMaxAggregateOutputType: { // field return type
    id: number; // Int!
    itemId: string | null; // String
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber: string | null; // String
    supplierId: number; // Int!
  }
  OrderItemMinAggregateOutputType: { // field return type
    id: number; // Int!
    itemId: string | null; // String
    orderId: number; // Int!
    quantity: number; // Float!
    receiptNumber: string | null; // String
    supplierId: number; // Int!
  }
  OrderItemSumAggregateOutputType: { // field return type
    id: number; // Int!
    orderId: number; // Int!
    quantity: number; // Float!
    supplierId: number; // Int!
  }
  OrderMaxAggregateOutputType: { // field return type
    date: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderMinAggregateOutputType: { // field return type
    date: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    supplierId: number; // Int!
  }
  OrderSumAggregateOutputType: { // field return type
    id: number; // Int!
    supplierId: number; // Int!
  }
  Query: { // field return type
    aggregateItem: NexusGenRootTypes['AggregateItem'] | null; // AggregateItem
    aggregateOrder: NexusGenRootTypes['AggregateOrder'] | null; // AggregateOrder
    aggregateOrderItem: NexusGenRootTypes['AggregateOrderItem'] | null; // AggregateOrderItem
    aggregateSupplier: NexusGenRootTypes['AggregateSupplier'] | null; // AggregateSupplier
    aggregateUser: NexusGenRootTypes['AggregateUser'] | null; // AggregateUser
    findFirstItem: NexusGenRootTypes['Item'] | null; // Item
    findFirstOrder: NexusGenRootTypes['Order'] | null; // Order
    findFirstOrderItem: NexusGenRootTypes['OrderItem'] | null; // OrderItem
    findFirstSupplier: NexusGenRootTypes['Supplier'] | null; // Supplier
    findFirstUser: NexusGenRootTypes['User'] | null; // User
    findManyItem: NexusGenRootTypes['Item'][]; // [Item!]!
    findManyItemCount: number; // Int!
    findManyOrder: NexusGenRootTypes['Order'][]; // [Order!]!
    findManyOrderCount: number; // Int!
    findManyOrderItem: NexusGenRootTypes['OrderItem'][]; // [OrderItem!]!
    findManyOrderItemCount: number; // Int!
    findManySupplier: NexusGenRootTypes['Supplier'][]; // [Supplier!]!
    findManySupplierCount: number; // Int!
    findManyUser: NexusGenRootTypes['User'][]; // [User!]!
    findManyUserCount: number; // Int!
    findUniqueItem: NexusGenRootTypes['Item'] | null; // Item
    findUniqueOrder: NexusGenRootTypes['Order'] | null; // Order
    findUniqueOrderItem: NexusGenRootTypes['OrderItem'] | null; // OrderItem
    findUniqueSupplier: NexusGenRootTypes['Supplier'] | null; // Supplier
    findUniqueUser: NexusGenRootTypes['User'] | null; // User
  }
  Supplier: { // field return type
    id: number; // Int!
    name: string; // String!
    Order: NexusGenRootTypes['Order'][]; // [Order!]!
    OrderItem: NexusGenRootTypes['OrderItem'][]; // [OrderItem!]!
  }
  SupplierAvgAggregateOutputType: { // field return type
    id: number; // Float!
  }
  SupplierCountAggregateOutputType: { // field return type
    _all: number; // Int!
    id: number; // Int!
    name: number | null; // Int
  }
  SupplierMaxAggregateOutputType: { // field return type
    id: number; // Int!
    name: string | null; // String
  }
  SupplierMinAggregateOutputType: { // field return type
    id: number; // Int!
    name: string | null; // String
  }
  SupplierSumAggregateOutputType: { // field return type
    id: number; // Int!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string | null; // String
    id: number; // Int!
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserAvgAggregateOutputType: { // field return type
    id: number; // Float!
  }
  UserCountAggregateOutputType: { // field return type
    _all: number; // Int!
    createdAt: number | null; // Int
    email: number | null; // Int
    id: number; // Int!
    name: number | null; // Int
    updatedAt: number | null; // Int
  }
  UserMaxAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    id: number; // Int!
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserMinAggregateOutputType: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    id: number; // Int!
    name: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserSumAggregateOutputType: { // field return type
    id: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  AggregateItem: { // field return type name
    count: 'ItemCountAggregateOutputType'
    max: 'ItemMaxAggregateOutputType'
    min: 'ItemMinAggregateOutputType'
  }
  AggregateOrder: { // field return type name
    avg: 'OrderAvgAggregateOutputType'
    count: 'OrderCountAggregateOutputType'
    max: 'OrderMaxAggregateOutputType'
    min: 'OrderMinAggregateOutputType'
    sum: 'OrderSumAggregateOutputType'
  }
  AggregateOrderItem: { // field return type name
    avg: 'OrderItemAvgAggregateOutputType'
    count: 'OrderItemCountAggregateOutputType'
    max: 'OrderItemMaxAggregateOutputType'
    min: 'OrderItemMinAggregateOutputType'
    sum: 'OrderItemSumAggregateOutputType'
  }
  AggregateSupplier: { // field return type name
    avg: 'SupplierAvgAggregateOutputType'
    count: 'SupplierCountAggregateOutputType'
    max: 'SupplierMaxAggregateOutputType'
    min: 'SupplierMinAggregateOutputType'
    sum: 'SupplierSumAggregateOutputType'
  }
  AggregateUser: { // field return type name
    avg: 'UserAvgAggregateOutputType'
    count: 'UserCountAggregateOutputType'
    max: 'UserMaxAggregateOutputType'
    min: 'UserMinAggregateOutputType'
    sum: 'UserSumAggregateOutputType'
  }
  BatchPayload: { // field return type name
    count: 'Int'
  }
  Item: { // field return type name
    category: 'String'
    description: 'String'
    id: 'String'
    name: 'String'
    OrderItems: 'OrderItem'
    saleType: 'saleType'
    snHerzelia: 'String'
    snWebSite: 'String'
  }
  ItemCountAggregateOutputType: { // field return type name
    _all: 'Int'
    category: 'Int'
    description: 'Int'
    id: 'Int'
    name: 'Int'
    saleType: 'Int'
    snHerzelia: 'Int'
    snWebSite: 'Int'
  }
  ItemMaxAggregateOutputType: { // field return type name
    category: 'String'
    description: 'String'
    id: 'String'
    name: 'String'
    saleType: 'saleType'
    snHerzelia: 'String'
    snWebSite: 'String'
  }
  ItemMinAggregateOutputType: { // field return type name
    category: 'String'
    description: 'String'
    id: 'String'
    name: 'String'
    saleType: 'saleType'
    snHerzelia: 'String'
    snWebSite: 'String'
  }
  Mutation: { // field return type name
    createManyItem: 'BatchPayload'
    createOneItem: 'Item'
    createOneOrder: 'Order'
    createOneOrderItem: 'OrderItem'
    createOneSupplier: 'Supplier'
    createOneUser: 'User'
    deleteManyItem: 'BatchPayload'
    deleteManyOrder: 'BatchPayload'
    deleteManyOrderItem: 'BatchPayload'
    deleteManySupplier: 'BatchPayload'
    deleteManyUser: 'BatchPayload'
    deleteOneItem: 'Item'
    deleteOneOrder: 'Order'
    deleteOneOrderItem: 'OrderItem'
    deleteOneSupplier: 'Supplier'
    deleteOneUser: 'User'
    updateManyItem: 'BatchPayload'
    updateManyOrder: 'BatchPayload'
    updateManyOrderItem: 'BatchPayload'
    updateManySupplier: 'BatchPayload'
    updateManyUser: 'BatchPayload'
    updateOneItem: 'Item'
    updateOneOrder: 'Order'
    updateOneOrderItem: 'OrderItem'
    updateOneSupplier: 'Supplier'
    updateOneUser: 'User'
    upsertOneItem: 'Item'
    upsertOneOrder: 'Order'
    upsertOneOrderItem: 'OrderItem'
    upsertOneSupplier: 'Supplier'
    upsertOneUser: 'User'
  }
  Order: { // field return type name
    date: 'DateTime'
    id: 'Int'
    items: 'OrderItem'
    supplier: 'Supplier'
    supplierId: 'Int'
  }
  OrderAvgAggregateOutputType: { // field return type name
    id: 'Float'
    supplierId: 'Float'
  }
  OrderCountAggregateOutputType: { // field return type name
    _all: 'Int'
    date: 'Int'
    id: 'Int'
    supplierId: 'Int'
  }
  OrderItem: { // field return type name
    id: 'Int'
    item: 'Item'
    itemId: 'String'
    Order: 'Order'
    orderId: 'Int'
    quantity: 'Float'
    receiptNumber: 'String'
    supplier: 'Supplier'
    supplierId: 'Int'
  }
  OrderItemAvgAggregateOutputType: { // field return type name
    id: 'Float'
    orderId: 'Float'
    quantity: 'Float'
    supplierId: 'Float'
  }
  OrderItemCountAggregateOutputType: { // field return type name
    _all: 'Int'
    id: 'Int'
    itemId: 'Int'
    orderId: 'Int'
    quantity: 'Int'
    receiptNumber: 'Int'
    supplierId: 'Int'
  }
  OrderItemMaxAggregateOutputType: { // field return type name
    id: 'Int'
    itemId: 'String'
    orderId: 'Int'
    quantity: 'Float'
    receiptNumber: 'String'
    supplierId: 'Int'
  }
  OrderItemMinAggregateOutputType: { // field return type name
    id: 'Int'
    itemId: 'String'
    orderId: 'Int'
    quantity: 'Float'
    receiptNumber: 'String'
    supplierId: 'Int'
  }
  OrderItemSumAggregateOutputType: { // field return type name
    id: 'Int'
    orderId: 'Int'
    quantity: 'Float'
    supplierId: 'Int'
  }
  OrderMaxAggregateOutputType: { // field return type name
    date: 'DateTime'
    id: 'Int'
    supplierId: 'Int'
  }
  OrderMinAggregateOutputType: { // field return type name
    date: 'DateTime'
    id: 'Int'
    supplierId: 'Int'
  }
  OrderSumAggregateOutputType: { // field return type name
    id: 'Int'
    supplierId: 'Int'
  }
  Query: { // field return type name
    aggregateItem: 'AggregateItem'
    aggregateOrder: 'AggregateOrder'
    aggregateOrderItem: 'AggregateOrderItem'
    aggregateSupplier: 'AggregateSupplier'
    aggregateUser: 'AggregateUser'
    findFirstItem: 'Item'
    findFirstOrder: 'Order'
    findFirstOrderItem: 'OrderItem'
    findFirstSupplier: 'Supplier'
    findFirstUser: 'User'
    findManyItem: 'Item'
    findManyItemCount: 'Int'
    findManyOrder: 'Order'
    findManyOrderCount: 'Int'
    findManyOrderItem: 'OrderItem'
    findManyOrderItemCount: 'Int'
    findManySupplier: 'Supplier'
    findManySupplierCount: 'Int'
    findManyUser: 'User'
    findManyUserCount: 'Int'
    findUniqueItem: 'Item'
    findUniqueOrder: 'Order'
    findUniqueOrderItem: 'OrderItem'
    findUniqueSupplier: 'Supplier'
    findUniqueUser: 'User'
  }
  Supplier: { // field return type name
    id: 'Int'
    name: 'String'
    Order: 'Order'
    OrderItem: 'OrderItem'
  }
  SupplierAvgAggregateOutputType: { // field return type name
    id: 'Float'
  }
  SupplierCountAggregateOutputType: { // field return type name
    _all: 'Int'
    id: 'Int'
    name: 'Int'
  }
  SupplierMaxAggregateOutputType: { // field return type name
    id: 'Int'
    name: 'String'
  }
  SupplierMinAggregateOutputType: { // field return type name
    id: 'Int'
    name: 'String'
  }
  SupplierSumAggregateOutputType: { // field return type name
    id: 'Int'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
  UserAvgAggregateOutputType: { // field return type name
    id: 'Float'
  }
  UserCountAggregateOutputType: { // field return type name
    _all: 'Int'
    createdAt: 'Int'
    email: 'Int'
    id: 'Int'
    name: 'Int'
    updatedAt: 'Int'
  }
  UserMaxAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
  UserMinAggregateOutputType: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    updatedAt: 'DateTime'
  }
  UserSumAggregateOutputType: { // field return type name
    id: 'Int'
  }
}

export interface NexusGenArgTypes {
  Item: {
    OrderItems: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: NexusGenInputs['OrderItemOrderByInput'] | null; // OrderItemOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
  }
  Mutation: {
    createManyItem: { // args
      data?: NexusGenInputs['ItemCreateInput'][] | null; // [ItemCreateInput!]
    }
    createOneItem: { // args
      data: NexusGenInputs['ItemCreateInput']; // ItemCreateInput!
    }
    createOneOrder: { // args
      data: NexusGenInputs['OrderCreateInput']; // OrderCreateInput!
    }
    createOneOrderItem: { // args
      data: NexusGenInputs['OrderItemCreateInput']; // OrderItemCreateInput!
    }
    createOneSupplier: { // args
      data: NexusGenInputs['SupplierCreateInput']; // SupplierCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteManyItem: { // args
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    deleteManyOrder: { // args
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    deleteManyOrderItem: { // args
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    deleteManySupplier: { // args
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    deleteManyUser: { // args
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    deleteOneItem: { // args
      where: NexusGenInputs['ItemWhereUniqueInput']; // ItemWhereUniqueInput!
    }
    deleteOneOrder: { // args
      where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
    }
    deleteOneOrderItem: { // args
      where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
    }
    deleteOneSupplier: { // args
      where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    updateManyItem: { // args
      data: NexusGenInputs['ItemUpdateManyMutationInput']; // ItemUpdateManyMutationInput!
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    updateManyOrder: { // args
      data: NexusGenInputs['OrderUpdateManyMutationInput']; // OrderUpdateManyMutationInput!
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    updateManyOrderItem: { // args
      data: NexusGenInputs['OrderItemUpdateManyMutationInput']; // OrderItemUpdateManyMutationInput!
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    updateManySupplier: { // args
      data: NexusGenInputs['SupplierUpdateManyMutationInput']; // SupplierUpdateManyMutationInput!
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    updateManyUser: { // args
      data: NexusGenInputs['UserUpdateManyMutationInput']; // UserUpdateManyMutationInput!
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    updateOneItem: { // args
      data: NexusGenInputs['ItemUpdateInput']; // ItemUpdateInput!
      where: NexusGenInputs['ItemWhereUniqueInput']; // ItemWhereUniqueInput!
    }
    updateOneOrder: { // args
      data: NexusGenInputs['OrderUpdateInput']; // OrderUpdateInput!
      where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
    }
    updateOneOrderItem: { // args
      data: NexusGenInputs['OrderItemUpdateInput']; // OrderItemUpdateInput!
      where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
    }
    updateOneSupplier: { // args
      data: NexusGenInputs['SupplierUpdateInput']; // SupplierUpdateInput!
      where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
    }
    updateOneUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    upsertOneItem: { // args
      create: NexusGenInputs['ItemCreateInput']; // ItemCreateInput!
      update: NexusGenInputs['ItemUpdateInput']; // ItemUpdateInput!
      where: NexusGenInputs['ItemWhereUniqueInput']; // ItemWhereUniqueInput!
    }
    upsertOneOrder: { // args
      create: NexusGenInputs['OrderCreateInput']; // OrderCreateInput!
      update: NexusGenInputs['OrderUpdateInput']; // OrderUpdateInput!
      where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
    }
    upsertOneOrderItem: { // args
      create: NexusGenInputs['OrderItemCreateInput']; // OrderItemCreateInput!
      update: NexusGenInputs['OrderItemUpdateInput']; // OrderItemUpdateInput!
      where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
    }
    upsertOneSupplier: { // args
      create: NexusGenInputs['SupplierCreateInput']; // SupplierCreateInput!
      update: NexusGenInputs['SupplierUpdateInput']; // SupplierUpdateInput!
      where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
    }
    upsertOneUser: { // args
      create: NexusGenInputs['UserCreateInput']; // UserCreateInput!
      update: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Order: {
    items: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: NexusGenInputs['OrderItemOrderByInput'] | null; // OrderItemOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
  }
  Query: {
    aggregateItem: { // args
      cursor?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
      distinct?: NexusGenEnums['ItemScalarFieldEnum'] | null; // ItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['ItemOrderByInput'] | null> | null; // [ItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    aggregateOrder: { // args
      cursor?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
      distinct?: NexusGenEnums['OrderScalarFieldEnum'] | null; // OrderScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderOrderByInput'] | null> | null; // [OrderOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    aggregateOrderItem: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderItemOrderByInput'] | null> | null; // [OrderItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    aggregateSupplier: { // args
      cursor?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
      distinct?: NexusGenEnums['SupplierScalarFieldEnum'] | null; // SupplierScalarFieldEnum
      orderBy?: Array<NexusGenInputs['SupplierOrderByInput'] | null> | null; // [SupplierOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    aggregateUser: { // args
      cursor?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      distinct?: NexusGenEnums['UserScalarFieldEnum'] | null; // UserScalarFieldEnum
      orderBy?: Array<NexusGenInputs['UserOrderByInput'] | null> | null; // [UserOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    findFirstItem: { // args
      cursor?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
      distinct?: NexusGenEnums['ItemScalarFieldEnum'] | null; // ItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['ItemOrderByInput'] | null> | null; // [ItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    findFirstOrder: { // args
      cursor?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
      distinct?: NexusGenEnums['OrderScalarFieldEnum'] | null; // OrderScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderOrderByInput'] | null> | null; // [OrderOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    findFirstOrderItem: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderItemOrderByInput'] | null> | null; // [OrderItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    findFirstSupplier: { // args
      cursor?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
      distinct?: NexusGenEnums['SupplierScalarFieldEnum'] | null; // SupplierScalarFieldEnum
      orderBy?: Array<NexusGenInputs['SupplierOrderByInput'] | null> | null; // [SupplierOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    findFirstUser: { // args
      cursor?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      distinct?: NexusGenEnums['UserScalarFieldEnum'] | null; // UserScalarFieldEnum
      orderBy?: Array<NexusGenInputs['UserOrderByInput'] | null> | null; // [UserOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    findManyItem: { // args
      cursor?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
      distinct?: NexusGenEnums['ItemScalarFieldEnum'] | null; // ItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['ItemOrderByInput'] | null> | null; // [ItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    findManyItemCount: { // args
      cursor?: NexusGenInputs['ItemWhereUniqueInput'] | null; // ItemWhereUniqueInput
      distinct?: NexusGenEnums['ItemScalarFieldEnum'] | null; // ItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['ItemOrderByInput'] | null> | null; // [ItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
    findManyOrder: { // args
      cursor?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
      distinct?: NexusGenEnums['OrderScalarFieldEnum'] | null; // OrderScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderOrderByInput'] | null> | null; // [OrderOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    findManyOrderCount: { // args
      cursor?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
      distinct?: NexusGenEnums['OrderScalarFieldEnum'] | null; // OrderScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderOrderByInput'] | null> | null; // [OrderOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    findManyOrderItem: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderItemOrderByInput'] | null> | null; // [OrderItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    findManyOrderItemCount: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: Array<NexusGenInputs['OrderItemOrderByInput'] | null> | null; // [OrderItemOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
    findManySupplier: { // args
      cursor?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
      distinct?: NexusGenEnums['SupplierScalarFieldEnum'] | null; // SupplierScalarFieldEnum
      orderBy?: Array<NexusGenInputs['SupplierOrderByInput'] | null> | null; // [SupplierOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    findManySupplierCount: { // args
      cursor?: NexusGenInputs['SupplierWhereUniqueInput'] | null; // SupplierWhereUniqueInput
      distinct?: NexusGenEnums['SupplierScalarFieldEnum'] | null; // SupplierScalarFieldEnum
      orderBy?: Array<NexusGenInputs['SupplierOrderByInput'] | null> | null; // [SupplierOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SupplierWhereInput'] | null; // SupplierWhereInput
    }
    findManyUser: { // args
      cursor?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      distinct?: NexusGenEnums['UserScalarFieldEnum'] | null; // UserScalarFieldEnum
      orderBy?: Array<NexusGenInputs['UserOrderByInput'] | null> | null; // [UserOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    findManyUserCount: { // args
      cursor?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      distinct?: NexusGenEnums['UserScalarFieldEnum'] | null; // UserScalarFieldEnum
      orderBy?: Array<NexusGenInputs['UserOrderByInput'] | null> | null; // [UserOrderByInput]
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    findUniqueItem: { // args
      where: NexusGenInputs['ItemWhereUniqueInput']; // ItemWhereUniqueInput!
    }
    findUniqueOrder: { // args
      where: NexusGenInputs['OrderWhereUniqueInput']; // OrderWhereUniqueInput!
    }
    findUniqueOrderItem: { // args
      where: NexusGenInputs['OrderItemWhereUniqueInput']; // OrderItemWhereUniqueInput!
    }
    findUniqueSupplier: { // args
      where: NexusGenInputs['SupplierWhereUniqueInput']; // SupplierWhereUniqueInput!
    }
    findUniqueUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Supplier: {
    Order: { // args
      cursor?: NexusGenInputs['OrderWhereUniqueInput'] | null; // OrderWhereUniqueInput
      distinct?: NexusGenEnums['OrderScalarFieldEnum'] | null; // OrderScalarFieldEnum
      orderBy?: NexusGenInputs['OrderOrderByInput'] | null; // OrderOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderWhereInput'] | null; // OrderWhereInput
    }
    OrderItem: { // args
      cursor?: NexusGenInputs['OrderItemWhereUniqueInput'] | null; // OrderItemWhereUniqueInput
      distinct?: NexusGenEnums['OrderItemScalarFieldEnum'] | null; // OrderItemScalarFieldEnum
      orderBy?: NexusGenInputs['OrderItemOrderByInput'] | null; // OrderItemOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['OrderItemWhereInput'] | null; // OrderItemWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}