export const itemArray = [
  {
    name: 'עגבניה אשכולות',
    description: 'עגבניה ישראלית איכותית, המומלצת ביותר',
    category: 'ירקות',
    id: '100010',
    saleType: 'UNIT',
    snWebSite: '2868170',
    snHerzelia: '0004',
  },
  {
    name: 'עגבניה תמר',
    description: 'עגבניה ישראלית איכותית - מתאימה מאוד לסלט, קלה לחיתוך',
    category: 'ירקות',
    id: '100011',
    saleType: 'UNIT',
    snWebSite: '2868171',
    snHerzelia: '00027',
  },
  {
    name: 'עגבניה חממה',
    description: 'עגבניה חממה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100012',
    saleType: 'UNIT',
    snWebSite: '2868172',
    snHerzelia: '000310',
  },
  {
    name: 'עגבניה מגי- מארז כ1.3 ק"ג',
    description: 'עגבניה מגי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100013',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2902852',
    snHerzelia: '000245',
  },
  {
    name: 'מלפפון',
    description: 'מלפפון מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100020',
    saleType: 'UNIT',
    snWebSite: '2868173',
    snHerzelia: '0002',
  },
  {
    name: 'מלפפון בייבי',
    description: 'מלפפון בייבי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100021',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אבוקדו "אטינגר"',
    description: 'אבוקדו "אטינגר" מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100030',
    saleType: 'UNIT',
    snWebSite: '2868174',
    snHerzelia: '00062',
  },
  {
    name: 'אבוקדו "האס"',
    description: 'אבוקדו "האס" מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100031',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח אדמה לבן גורמה- מארז כ3 ק"ג',
    description: 'תפוח אדמה לבן פרימיום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100040',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868175',
    snHerzelia: '00013',
  },
  {
    name: 'תפוח אדמה אדום גורמה- מארז כ3 ק"ג',
    description: 'תפוח אדמה אדום גורמה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100041',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2902854',
    snHerzelia: '00304',
  },
  {
    name: 'תפוח אדמה לבן תפזורת',
    description: 'תפוח אדמה לבן תפזורת מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100042',
    saleType: 'UNIT',
    snWebSite: '2902855',
    snHerzelia: '00011',
  },
  {
    name: 'תפוח אדמה אדום תפזורת',
    description: 'תפוח אדמה אדום תפזורת מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100043',
    saleType: 'UNIT',
    snWebSite: '2902856',
    snHerzelia: '00012',
  },
  {
    name: 'תפוח אדמה סגול',
    description: 'תפוח אדמה סגול מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100044',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח אדמה ראטה',
    description: 'תפוח אדמה ראטה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100045',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח אדמה בייבי גורמה לבן- מארז כ1.5 ק"ג',
    description:
      'תפוח אדמה בייבי גורמה לבן- מארז כ1.5 ק"ג מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100046',
    saleType: 'WIEGHT_PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בצל',
    description: 'בצל מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100050',
    saleType: 'UNIT',
    snWebSite: '2868176',
    snHerzelia: '00017',
  },
  {
    name: 'בצל סגול',
    description: 'בצל סגול מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100051',
    saleType: 'UNIT',
    snWebSite: '2868177',
    snHerzelia: '00018',
  },
  {
    name: 'בצל שאלוט',
    description: 'בצל שאלוט מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100052',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בצל פנינה',
    description: 'בצל פנינה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100053',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חציל',
    description: 'חציל מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100060',
    saleType: 'UNIT',
    snWebSite: '2868178',
    snHerzelia: '0005',
  },
  {
    name: 'חציל בלאדי',
    description: 'חציל בלאדי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100061',
    saleType: 'UNIT',
    snWebSite: '2868179',
    snHerzelia: '0006',
  },
  {
    name: 'חצילונים',
    description: 'חצילונים מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100062',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חציל יפני',
    description: 'חציל יפני מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100063',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גזר',
    description: 'גזר מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100070',
    saleType: 'UNIT',
    snWebSite: '2868180',
    snHerzelia: 'צריך להקים',
  },
  {
    name: 'גזר מארז- כ1.3 ק"ג',
    description: 'גזר מארז מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100071',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2902857',
    snHerzelia: '00020',
  },
  {
    name: 'גזר צבעוני מארז- כ700 גרם',
    description: 'גזר צבעוני מארז- כ700 גרם מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100072',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חטיפי גזר',
    description: 'חטיפי גזר מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100073',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כרוב',
    description: 'כרוב מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100080',
    saleType: 'UNIT',
    snWebSite: '2868181',
    snHerzelia: '00024',
  },
  {
    name: 'כרוב סגול',
    description: 'כרוב סגול מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100081',
    saleType: 'UNIT',
    snWebSite: '2868182',
    snHerzelia: '00025',
  },
  {
    name: 'קישוא',
    description: 'קישוא מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100090',
    saleType: 'UNIT',
    snWebSite: '2868183',
    snHerzelia: '0007',
  },
  {
    name: 'זוקיני',
    description: 'זוקיני מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100091',
    saleType: 'UNIT',
    snWebSite: '2902858',
    snHerzelia: '0008',
  },
  {
    name: 'קישוא עגול',
    description: 'קישוא עגול מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100092',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'לימון',
    description: 'לימון מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100100',
    saleType: 'UNIT',
    snWebSite: '2868184',
    snHerzelia: '00069',
  },
  {
    name: 'לימון ירוק',
    description: 'לימון ירוק מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100101',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ליים',
    description: 'ליים מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100102',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל אדום',
    description: 'פלפל אדום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100110',
    saleType: 'UNIT',
    snWebSite: '2868185',
    snHerzelia: '00029',
  },
  {
    name: 'פלפל צהוב',
    description: 'פלפל צהוב מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100111',
    saleType: 'UNIT',
    snWebSite: '2868186',
    snHerzelia: '00031',
  },
  {
    name: 'פלפל כתום',
    description: 'פלפל כתום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100112',
    saleType: 'UNIT',
    snWebSite: '2868187',
    snHerzelia: '00032',
  },
  {
    name: 'פלפל חריף',
    description: 'פלפל חריף מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100113',
    saleType: 'UNIT',
    snWebSite: '2868188',
    snHerzelia: '00033',
  },
  {
    name: 'פלפל ירוק',
    description: 'פלפל ירוק מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100114',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל שושקה',
    description: 'פלפל שושקה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100115',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פלפל צ'ילי",
    description: "פלפל צ'ילי מתוצרת ישראלית איכותית",
    category: 'ירקות',
    id: '100116',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל מתוק ללא גרעינים',
    description: 'פלפל מתוק ללא גרעינים מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100117',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פלפל צ'ילי ירוק",
    description: "פלפל צ'ילי ירוק מתוצרת ישראלית איכותית",
    category: 'ירקות',
    id: '100118',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל חלפניו טרי',
    description: 'פלפל חלפניו טרי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100119',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שום',
    description: 'שום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100120',
    saleType: 'UNIT',
    snWebSite: '2868189',
    snHerzelia: '00034',
  },
  {
    name: 'שום מארז',
    description: 'שום מארז מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100121',
    saleType: 'PACK',
    snWebSite: '2902861',
    snHerzelia: '000235',
  },
  {
    name: 'שום פנינה (סולו)',
    description: 'שום פנינה (סולו) מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100122',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בטטה',
    description: 'בטטה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100130',
    saleType: 'UNIT',
    snWebSite: '2868190',
    snHerzelia: '00016',
  },
  {
    name: 'בטטה מיני',
    description: 'בטטה מיני מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100131',
    saleType: 'UNIT',
    snWebSite: '2902853',
    snHerzelia: '00305',
  },
  {
    name: 'בטטה סגולה',
    description: 'בטטה סגולה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100132',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בטטה לבנה',
    description: 'בטטה לבנה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100133',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בטטה בייבי מארז',
    description: 'בטטה בייבי מארז מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100134',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סלק',
    description: 'סלק מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100140',
    saleType: 'UNIT',
    snWebSite: '2868191',
    snHerzelia: '0009',
  },
  {
    name: 'סלק אדום מקולף ומבושל בואקום',
    description: 'סלק אדום מקולף ומבושל בואקום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100141',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כרובית',
    description: 'כרובית מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100150',
    saleType: 'UNIT',
    snWebSite: '2868192',
    snHerzelia: '00026',
  },
  {
    name: 'קולורבי',
    description: 'קולורבי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100160',
    saleType: 'UNIT',
    snWebSite: '2868193',
    snHerzelia: '000123',
  },
  {
    name: 'שומר',
    description: 'שומר מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100170',
    saleType: 'UNIT',
    snWebSite: '2868194',
    snHerzelia: '00036',
  },
  {
    name: 'עגבניות שרי',
    description: 'עגבניות שרי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100180',
    saleType: 'PACK',
    snWebSite: '2868195',
    snHerzelia: '00042',
  },
  {
    name: 'שרי לובלו תמר- מארז כ1.1 ק"ג',
    description: 'שרי לובלו תמר מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100181',
    saleType: 'KG',
    snWebSite: '2868196',
    snHerzelia: '00039',
  },
  {
    name: 'שרי ליקופן- מארז כ1.25',
    description: 'שרי ליקופן- מארז כ1.25 מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100182',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שרי כתום',
    description: 'שרי כתום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100183',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שרי תמר- מארז כ1.2 ק"ג',
    description:
      "שרי תמר- מארז כ1.2 ק\"ג מתוצרת ישראלית איכותיתזן יותר מעוגל ופחות מאורך מה'שרי לובלו תמר' מאוד טעימות ומתוקות",
    category: 'ירקות',
    id: '100184',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שרי ויטני',
    description: 'שרי ויטני מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100185',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דלעת',
    description: 'דלעת מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100190',
    saleType: 'KG',
    snWebSite: '2868197',
    snHerzelia: '00022',
  },
  {
    name: 'דלעת יפנית',
    description: 'דלעת יפנית מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100191',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דלעת ספגטי',
    description: 'דלעת ספגטי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100192',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דלעת מיני',
    description: 'דלעת מיני מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100193',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סלרי שורש',
    description: 'סלרי שורש מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100200',
    saleType: 'UNIT',
    snWebSite: '2868198',
    snHerzelia: '000109',
  },
  {
    name: 'ארטישוק',
    description: 'ארטישוק מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100210',
    saleType: 'UNIT',
    snWebSite: '2868199',
    snHerzelia: '00014',
  },
  {
    name: 'ארטישוק ירושלמי',
    description: 'ארטישוק ירושלמי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100220',
    saleType: 'UNIT',
    snWebSite: '2868200',
    snHerzelia: '000133',
  },
  {
    name: 'לפת',
    description: 'לפת מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100230',
    saleType: 'UNIT',
    snWebSite: '2868201',
    snHerzelia: '00010',
  },
  {
    name: 'צנון',
    description: 'צנון מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100240',
    saleType: 'UNIT',
    snWebSite: '2868202',
    snHerzelia: '000215',
  },
  {
    name: 'צנונית',
    description: 'צנונית מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100250',
    saleType: 'UNIT',
    snWebSite: '2868203',
    snHerzelia: '000107',
  },
  {
    name: 'צנונית בייבי',
    description: 'צנונית בייבי מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100251',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דלורית',
    description: 'דלורית מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100260',
    saleType: 'UNIT',
    snWebSite: '2868204',
    snHerzelia: '00021',
  },
  {
    name: 'חזרת',
    description: 'חזרת מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100270',
    saleType: 'UNIT',
    snWebSite: '2868205',
    snHerzelia: 'צריך להקים',
  },
  {
    name: 'דלעת ערמונים',
    description: 'דלעת ערמונים מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100280',
    saleType: 'UNIT',
    snWebSite: '2868206',
    snHerzelia: '22',
  },
  {
    name: 'פלפלונים',
    description: 'פלפלונים מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100290',
    saleType: 'PACK',
    snWebSite: '2868207',
    snHerzelia: '00044',
  },
  {
    name: 'שורש פטרוזיליה',
    description: 'שורש פטרוזיליה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100300',
    saleType: 'UNIT',
    snWebSite: '2868208',
    snHerzelia: '000211',
  },
  {
    name: 'שעועית ירוקה',
    description: 'שעועית ירוקה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100310',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שעועית צהובה',
    description: 'שעועית צהובה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100311',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שעועית רחבה',
    description: 'שעועית רחבה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100312',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'במיה',
    description: 'במיה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100320',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אנדיב לבן',
    description: 'אנדיב לבן מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100330',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אנדיב אדום',
    description: 'אנדיב אדום מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100331',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'לוביה',
    description: 'לוביה מתוצרת ישראלית איכותית',
    category: 'ירקות',
    id: '100340',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בננה',
    description: 'בננה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200010',
    saleType: 'UNIT',
    snWebSite: '2868209',
    snHerzelia: '0001',
  },
  {
    name: 'תות',
    description: 'תות מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200020',
    saleType: 'KG',
    snWebSite: '2868210',
    snHerzelia: '00060',
  },
  {
    name: 'תות- מארז כ250 גרם',
    description: 'תות- מארז כ250 גרם מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200021',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תות- מארז כ500 גרם',
    description: 'תות- מארז כ500 גרם מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200022',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח חרמון',
    description: 'תפוח חרמון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200030',
    saleType: 'UNIT',
    snWebSite: '2868211',
    snHerzelia: '00053',
  },
  {
    name: 'תפוח פינק ליידי',
    description: 'תפוח פינק ליידי מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200031',
    saleType: 'UNIT',
    snWebSite: '2868212',
    snHerzelia: '00055',
  },
  {
    name: 'תפוח ירוק',
    description: 'תפוח ירוק מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200032',
    saleType: 'UNIT',
    snWebSite: '2868213',
    snHerzelia: '00052',
  },
  {
    name: 'תפוח זהוב',
    description: 'תפוח זהוב מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200033',
    saleType: 'UNIT',
    snWebSite: '2868214',
    snHerzelia: '00051',
  },
  {
    name: 'תפוח אודם',
    description: 'תפוח אודם מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200034',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח פינק ליידי ישראלי ללא דונג',
    description: 'תפוח פינק ליידי ישראלי ללא דונג מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200035',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תפוח "רד מון"',
    description: 'תפוח "רד מון" ייבוא מאיטליה',
    category: 'פירות',
    id: '200036',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלון',
    description: 'מלון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200040',
    saleType: 'UNIT',
    snWebSite: '2868215',
    snHerzelia: '00071',
  },
  {
    name: 'מלון גליה',
    description: 'מלון גליה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200041',
    saleType: 'UNIT',
    snWebSite: '2868216',
    snHerzelia: '00306',
  },
  {
    name: 'מלון בון בון',
    description: 'מלון בון בון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200042',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלון ספרדי',
    description: 'מלון ספרדי מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200043',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלון גולדן',
    description: 'מלון גולדן מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200044',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלון שרנטה',
    description: 'מלון שרנטה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200045',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אגס',
    description: 'אגס מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200050',
    saleType: 'UNIT',
    snWebSite: '2868217',
    snHerzelia: '00063',
  },
  {
    name: 'אפרסמון',
    description: 'אפרסמון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200060',
    saleType: 'UNIT',
    snWebSite: '2868218',
    snHerzelia: '00066',
  },
  {
    name: 'קיווי',
    description: 'קיווי מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200070',
    saleType: 'UNIT',
    snWebSite: '2868219',
    snHerzelia: '00089',
  },
  {
    name: 'קיווי צהוב',
    description: 'קיווי צהוב מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200071',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אבטיח',
    description: 'אבטיח מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200080',
    saleType: 'UNIT',
    snWebSite: '2868220',
    snHerzelia: '00065',
  },
  {
    name: 'חצי אבטיח',
    description: 'חצי אבטיח מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200081',
    saleType: 'UNIT',
    snWebSite: '2902863',
    snHerzelia: 'לא רלוונטי לקופה',
  },
  {
    name: 'תפוז',
    description: 'תפוז מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200090',
    saleType: 'UNIT',
    snWebSite: '2868221',
    snHerzelia: '00047',
  },
  {
    name: 'תפוז אדום',
    description: 'תפוז אדום מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200091',
    saleType: 'UNIT',
    snWebSite: '2868222',
    snHerzelia: 'צריך להקים',
  },
  {
    name: 'תפוז מארז- מארז כ2.5 ק"ג',
    description: 'תפוז מארז מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200092',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2902859',
    snHerzelia: '00048',
  },
  {
    name: 'קלמנטינה',
    description: 'קלמנטינה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200100',
    saleType: 'UNIT',
    snWebSite: '2868223',
    snHerzelia: '000122',
  },
  {
    name: 'אשכולית',
    description: 'אשכולית מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200110',
    saleType: 'UNIT',
    snWebSite: '2868224',
    snHerzelia: '00067',
  },
  {
    name: 'אשכולית אדומה',
    description: 'אשכולית אדומה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200111',
    saleType: 'UNIT',
    snWebSite: '2868225',
    snHerzelia: '00068',
  },
  {
    name: 'פומלה',
    description: 'פומלה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200120',
    saleType: 'UNIT',
    snWebSite: '2868226',
    snHerzelia: '000205',
  },
  {
    name: 'פומלה מקולפת ומוכנה למאכל',
    description: 'פומלה מקולפת ומוכנה למאכל מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200121',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פומלה אדומה',
    description: 'פומלה אדומה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200122',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פומלית',
    description: 'פומלית מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200130',
    saleType: 'UNIT',
    snWebSite: '2868227',
    snHerzelia: '000207',
  },
  {
    name: 'ענבים ירוקים- מארז כ1.1 ק"ג',
    description: 'ענבים ירוקים- מארז כ1.1 ק"ג מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200150',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868228',
    snHerzelia: '00079',
  },
  {
    name: 'ענבים שחורים- מארז כ1.1 ק"ג',
    description: 'ענבים שחורים- מארז כ1.1 ק"ג מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200151',
    saleType: 'WIEGHT_PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס S',
    description: 'אננס S מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200160',
    saleType: 'UNIT',
    snWebSite: '2868229',
    snHerzelia: '00096',
  },
  {
    name: 'אננס M',
    description: 'אננס M מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200161',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס L',
    description: 'אננס L מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200162',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס XL',
    description: 'אננס XL מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200163',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס XXL',
    description: 'אננס XXL מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200164',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס קווין קטן',
    description: 'אננס קווין קטן מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200165',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס קווין M',
    description: 'אננס קווין M מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200166',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס קווין L',
    description: 'אננס קווין L מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200167',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אננס קווין XL',
    description: 'אננס קווין XL מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200168',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שסק',
    description: 'שסק מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200170',
    saleType: 'UNIT',
    snWebSite: '2868230',
    snHerzelia: '00061',
  },
  {
    name: 'רימון',
    description: 'רימון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200180',
    saleType: 'UNIT',
    snWebSite: '2868231',
    snHerzelia: 'צריך להקים',
  },
  {
    name: 'גרגירי רימון',
    description: 'גרגירי רימון מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200181',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פסיפלורה',
    description: 'פסיפלורה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200190',
    saleType: 'PACK',
    snWebSite: '2868232',
    snHerzelia: '1006',
  },
  {
    name: 'אוכמניות',
    description: 'אוכמניות מתוצרת איכותית',
    category: 'פירות',
    id: '200200',
    saleType: 'PACK',
    snWebSite: '2868233',
    snHerzelia: '00092',
  },
  {
    name: 'תמר מג\'הול אורגני 1 ק"ג "דקל הבקעה"',
    description:
      'תמר מג\'הול אורגני מתוצרת ישראלית איכותית, מארז 1 ק"ג משק "דקל הבקעה"',
    category: 'פירות',
    id: '200210',
    saleType: 'PACK',
    snWebSite: '2868234',
    snHerzelia: '00058',
  },
  {
    name: 'תמר מג\'הול 1 ק"ג "דקל הבקעה"',
    description:
      'תמר מג\'הול אורגני מתוצרת ישראלית איכותית, מארז 1 ק"ג משק "דקל הבקעה"',
    category: 'פירות',
    id: '200211',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תמר דקל נור כ400 גרם',
    description: 'תמר דקל נור כ400 גרם מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200212',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קוקוס',
    description: 'קוקוס מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200220',
    saleType: 'UNIT',
    snWebSite: '2868235',
    snHerzelia: '000216',
  },
  {
    name: 'קוקוס מקולף XL מוכן לשתייה',
    description: 'קוקוס מקולף XL מוכן לשתייה',
    category: 'פירות',
    id: '200221',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נקטרינה',
    description: 'נקטרינה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200230',
    saleType: 'UNIT',
    snWebSite: '2902848',
    snHerzelia: '00077',
  },
  {
    name: 'פפאיה ירוקה',
    description: 'פפאיה ירוקה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200240',
    saleType: 'UNIT',
    snWebSite: '2902849',
    snHerzelia: '00082',
  },
  {
    name: 'פפאיה צהובה',
    description: 'פפאיה צהובה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200241',
    saleType: 'UNIT',
    snWebSite: '2902850',
    snHerzelia: '00081',
  },
  {
    name: 'אפרסק',
    description: 'אפרסק מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200250',
    saleType: 'UNIT',
    snWebSite: '2902860',
    snHerzelia: '00075',
  },
  {
    name: 'אפרסק פיתה',
    description: 'אפרסק פיתה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200251',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שזיף',
    description: 'שזיף מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200260',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שזיף צהוב',
    description: 'שזיף צהוב מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200261',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שזיף אבטיח',
    description: 'שזיף אבטיח מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200262',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'משמש',
    description: 'משמש מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200270',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דובדבן',
    description: 'דובדבן מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200280',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '000295',
  },
  {
    name: 'פירות יער- פטל אדום',
    description: 'פירות יער- פטל אדום מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200290',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פירות יער- פטל שחור',
    description: 'פירות יער- פטל שחור מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200291',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דומדמניות',
    description: 'דומדמניות מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200292',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "ליצ'י",
    description: "ליצ'י מתוצרת ישראלית איכותית",
    category: 'פירות',
    id: '200300',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "ליצ'י במשקל",
    description: "ליצ'י במשקל מתוצרת ישראלית איכותית",
    category: 'פירות',
    id: '200301',
    saleType: 'KG',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תאנה',
    description: 'תאנה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200310',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תאנה באלדי',
    description: 'תאנה באלדי מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200311',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מנגו "שלי"',
    description: 'מנגו "שלי" מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200320',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מנגו "מאיה"',
    description: 'מנגו "מאיה" מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200321',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מנגו "עומר"',
    description: 'מנגו "עומר" מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200322',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מנגו "קיט"',
    description: 'מנגו "קיט" מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200323',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סברס',
    description: 'סברס מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200330',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פיטאיה "פרי הדרקון"',
    description: 'פיטאיה "פרי הדרקון" מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200340',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פיטאיה "פרי הדרקון" צהובה',
    description: 'פיטאיה "פרי הדרקון" צהובה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200341',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חבוש',
    description: 'חבוש מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200350',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גויאבה',
    description: 'גויאבה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200360',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גויאבה אדומה',
    description: 'גויאבה אדומה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200361',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קרמבולה',
    description: 'קרמבולה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200370',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אנונה',
    description: 'אנונה מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200380',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ערמונים- מארז כ1 ק"ג',
    description: 'ערמונים- מארז כ1 ק"ג מתוצרת ישראלית איכותית',
    category: 'פירות',
    id: '200390',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כוסברה',
    description: 'כוסברה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300010',
    saleType: 'PACK',
    snWebSite: '2868236',
    snHerzelia: '00099',
  },
  {
    name: 'פטרוזילה',
    description: 'פטרוזילה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300020',
    saleType: 'PACK',
    snWebSite: '2868237',
    snHerzelia: '000100',
  },
  {
    name: 'שמיר',
    description: 'שמיר מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300030',
    saleType: 'PACK',
    snWebSite: '2868238',
    snHerzelia: '00098',
  },
  {
    name: 'נענע',
    description: 'נענע מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300040',
    saleType: 'PACK',
    snWebSite: '2868239',
    snHerzelia: '000105',
  },
  {
    name: 'בזיליקום',
    description: 'בזיליקום מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300050',
    saleType: 'PACK',
    snWebSite: '2868240',
    snHerzelia: '00097',
  },
  {
    name: 'שיבא',
    description: 'שיבא מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300060',
    saleType: 'PACK',
    snWebSite: '2868241',
    snHerzelia: '000113',
  },
  {
    name: 'עירית',
    description: 'עירית מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300070',
    saleType: 'PACK',
    snWebSite: '2868242',
    snHerzelia: '000116',
  },
  {
    name: 'טימין',
    description: 'טימין מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300080',
    saleType: 'PACK',
    snWebSite: '2868243',
    snHerzelia: '000115',
  },
  {
    name: 'בצל ירוק',
    description: 'בצל ירוק מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300090',
    saleType: 'PACK',
    snWebSite: '2868244',
    snHerzelia: '000103',
  },
  {
    name: 'חסה',
    description: 'חסה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300100',
    saleType: 'UNIT',
    snWebSite: '2868245',
    snHerzelia: '000101',
  },
  {
    name: 'חסה עגולה',
    description: 'חסה עגולה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300101',
    saleType: 'UNIT',
    snWebSite: '2868246',
    snHerzelia: '000102',
  },
  {
    name: 'חסה סלנובה',
    description: 'חסה סלנובה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300102',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'לבבות חסה',
    description: 'לבבות חסה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300103',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חסה מסולסלת הידרופונית',
    description: 'חסה מסולסלת הידרופונית מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300104',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סלרי עלים',
    description: 'סלרי עלים מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300110',
    saleType: 'UNIT',
    snWebSite: '2868247',
    snHerzelia: '000108',
  },
  {
    name: "ג'ינג'ר",
    description: "ג'ינג'ר מתוצרת ישראלית איכותית",
    category: 'ירק ועשבי תיבול',
    id: '300120',
    saleType: 'UNIT',
    snWebSite: '2868248',
    snHerzelia: '00019',
  },
  {
    name: 'מנגולד',
    description: 'מנגולד מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300130',
    saleType: 'PACK',
    snWebSite: '2868249',
    snHerzelia: '000117',
  },
  {
    name: 'תרד',
    description: 'תרד מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300140',
    saleType: 'PACK',
    snWebSite: '2868250',
    snHerzelia: '000104',
  },
  {
    name: 'תרד גוליבר',
    description: 'תרד גוליבר מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300141',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ברוקולי',
    description: 'ברוקולי מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300150',
    saleType: 'PACK',
    snWebSite: '2868251',
    snHerzelia: '000120',
  },
  {
    name: 'נבטים',
    description: 'נבטים מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300160',
    saleType: 'PACK',
    snWebSite: '2868252',
    snHerzelia: '000196',
  },
  {
    name: 'פטריות שמפיניון',
    description: 'פטריות שמפיניון מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300170',
    saleType: 'PACK',
    snWebSite: '2868253',
    snHerzelia: '000118',
  },
  {
    name: 'פטריות פורטבלו',
    description: 'פטריות פורטבלו מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300171',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטריות סטייק שמפניון',
    description: 'פטריות סטייק שמפניון מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300172',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטריות סטייק פורטבחלו',
    description: 'פטריות סטייק פורטבחלו מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300173',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'צמד פטריות שמפניון + פורטבלו',
    description: 'צמד פטריות שמפניון + פורטבלו מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300174',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פטריות שימג'י' לבנות",
    description:
      "פטריות השימג'י עשירות בחומרים נוגדי-חִמצון, מחייבת בישול קצר מאוד, השימג'י עמידה מאוד בבישול ובהקפצה וניתן לשלבה במאכלים רבים",
    category: 'ירק ועשבי תיבול',
    id: '300175',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פטריות שימג'י' חומות",
    description:
      "פטריות השימג'י עשירות בחומרים נוגדי-חִמצון, מחייבת בישול קצר מאוד, השימג'י עמידה מאוד בבישול ובהקפצה וניתן לשלבה במאכלים רבים",
    category: 'ירק ועשבי תיבול',
    id: '300176',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כרישה',
    description: 'כרישה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300180',
    saleType: 'UNIT',
    snWebSite: '2868254',
    snHerzelia: '000106',
  },
  {
    name: 'גרגיר נחלים',
    description: 'גרגיר נחלים מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300190',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מיקס עלים לסלט',
    description:
      'גידולים הידרופוניים (על מים) ישראלים- עלי סלנובה, עלי תרד ועלי סלק',
    category: 'ירק ועשבי תיבול',
    id: '300200',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'רוקט',
    description: 'רוקט מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300210',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אספרגוס',
    description: 'אספרגוס מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300220',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קייל כרוב על',
    description: 'קייל כרוב על מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300230',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'רוזמרין',
    description: 'רוזמרין מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300240',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מרווה',
    description: 'מרווה מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300250',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אורגנו',
    description: 'אורגנו מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300260',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "באק צ'וי",
    description: "באק צ'וי מתוצרת ישראלית איכותית",
    category: 'ירק ועשבי תיבול',
    id: '300270',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שורש כורכום',
    description: 'שורש כורכום מתוצרת ישראלית איכותית',
    category: 'ירק ועשבי תיבול',
    id: '300280',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמן זית משק טנדט 750 מ"ל',
    description:
      'שמן זית משק טנדט 750 מ"ל מתוצרת ישראלית איכותית, כתית מעולה מכבישה קרה, זן ברנע, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500010',
    saleType: 'UNIT',
    snWebSite: '2868255',
    snHerzelia: '000307',
  },
  {
    name: 'שמן זית משק טנדט 2 ליטר',
    description:
      'שמן זית משק טנדט מתוצרת ישראלית איכותית, זן ברנע, כתית מעולה מכבישה קרה, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500011',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמן זית ענאל 750 מ"ל משק שמחוני',
    description:
      'שמן זית ענאל 750 מ"ל מתוצרת ישראלית איכותית, שמן זית מזן פיקואל כתית מעולה כבישה קרה, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500020',
    saleType: 'UNIT',
    snWebSite: '2868256',
    snHerzelia: '000224',
  },
  {
    name: 'שמן זית ענאל 1 ליטר משק שמחוני',
    description:
      'שמן זית ענאל מתוצרת ישראלית איכותית, שמן זית מזן ברנע כתית מעולה כבישה קרה, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500021',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמן זית ענאל 2 ליטר משק שמחוני',
    description:
      'שמן זית ענאל מתוצרת ישראלית איכותית, שמן זית מזן ברנע כתית מעולה כבישה קרה, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500022',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמן זית ענאל 4 ליטר משק שמחוני',
    description:
      'שמן זית ענאל מתוצרת ישראלית איכותית, שמן זית מזן ברנע כתית מעולה כבישה קרה, חמיצות מרבית 0.5% ',
    category: 'מוצרי מדף',
    id: '500023',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דבש פרחי שדה 350 גרם',
    description: 'דבש פרחי שדה 350 גרם מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500030',
    saleType: 'UNIT',
    snWebSite: '2868257',
    snHerzelia: '100',
  },
  {
    name: 'דבש פרחי שדה 1 ק"ג',
    description: 'דבש פרחי שדה 1 ק"ג מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500031',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דבש פריחת אבוקדו 1 ק"ג',
    description: 'דבש פריחת אבוקדו 1 ק"ג מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500032',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דבש פריחת אבוקדו 350 גרם',
    description: 'דבש פריחת אבוקדו 350 גרם מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500033',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דבש פריחת אקליפטוס 1 ק"ג',
    description: 'דבש פריחת אקליפטוס 1 ק"ג מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500034',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'דבש פריחת אקליפטוס 350 גרם',
    description: 'דבש פריחת אקליפטוס 350 גרם מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500035',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גרנולה עשירה תוצרת בית- מארז כ250 גרם',
    description:
      'גרנולה עשירה מאוד, מכילה:\nקשיו, אוזי מלך, פקאן, אוכמניות מיובשות, גרעיני דלעת, אננס מיובש, קוקוס מיובש, שקד פרוס, אגוזי לוז, דבש ושמן זית מובחר\nכל האגוזים והפירות טבעיים, ללא תוספת סוכר ובאיכות מעולה',
    category: 'מוצרי מדף',
    id: '500040',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נפלאות המורינגה',
    description: 'נפלאות המורינגה מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500041',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נפלאות המורינגה אבקה',
    description: 'נפלאות המורינגה אבקה מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500042',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ביצים גודל L תבנית 30 ביצים',
    description: 'ביצים גודל L תבנית 30 ביצים מתוצרת ישראלית איכותית',
    category: 'מוצרי מדף',
    id: '500050',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'לחם מחמצת- שיפון אגוזים',
    description:
      'לחם מחמצת- שיפון אגוזים מתוצרת מאפיית המוציא לחם\nמוצרי המאפה נאפים באיכות ובחומרים השובחים ביותר ומעובדים בעבודת יד ללא חומרים משמרים ',
    category: 'מוצרי מדף',
    id: '500060',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמן זית אסי- עמק המעיינות 750 מ"ל',
    description:
      'שמן זית אסי- עמק המעיינות 750 מ"ל מתוצרת ישראלית איכותית, כתית מעולה מכבישה קרה, חמיצות מרבית 0.8% ',
    category: 'מוצרי מדף',
    id: '500070',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פפריקה מתוקה 120 גרם',
    description:
      'פפריקה מתוקה 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510010',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פפריקה מתוקה ללא שמן 100 גרם',
    description:
      'פפריקה מתוקה ללא שמן 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510011',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פפריקה מתוקה מעושנת 100 גרם',
    description:
      'פפריקה מתוקה מעושנת 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510012',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פפריקה חריפה 120 גרם',
    description:
      'פפריקה חריפה 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510013',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פפריקה מתוקה גרוסה 100 גרם',
    description:
      'פפריקה מתוקה גרוסה 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510014',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פפריקה מתוקה אריזת חיסכון 400 גר'",
    description:
      "פפריקה מתוקה אריזת חיסכון 400 גר' מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510015',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פפריקה מתוקה ללא שמן אריזת חיסכון 400 גר'",
    description:
      "פפריקה מתוקה ללא שמן אריזת חיסכון 400 גר' מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510016',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כמון 120 גרם',
    description: 'כמון 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510020',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כורכום 120 גרם',
    description:
      'כורכום 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510030',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל שחור טחון 100 גרם',
    description:
      'פלפל שחור טחון 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510040',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל שחור גרוס 90 גרם',
    description:
      'פלפל שחור גרוס 90 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510041',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל שחור שלם 100 גרם',
    description:
      'פלפל שחור שלם 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510042',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'זעתר ביתי 100 גרם',
    description:
      'זעתר ביתי 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510050',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל לבן 80 גרם',
    description:
      'פלפל לבן 80 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510060',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קינמון טחון 120 גרם',
    description:
      'קינמון טחון 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510070',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קינמון שלום 80 גרם',
    description:
      'קינמון שלום 80 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510071',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "צ'ילי גרוס 100 גרם",
    description:
      "צ'ילי גרוס 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510080',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פילדלפיה 100 גרם',
    description:
      'פילדלפיה 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510090',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אגוז מוסקט טחון 40 גרם',
    description:
      'אגוז מוסקט טחון 40 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510100',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "חוויאג' למרק 100 גרם ",
    description:
      "חוויאג' למרק 100 גרם  מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510110',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תערובת בהרט 60 גרם',
    description:
      'תערובת בהרט 60 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510120',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תערובת ראס אל חנות 60 גרם',
    description:
      'תערובת ראס אל חנות 60 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510130',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אורגנו 60 גרם',
    description: 'אורגנו 60 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510140',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בזיליקום 45 גרם',
    description:
      'בזיליקום 45 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510150',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תבלין על האש ולסטייק 100 גרם',
    description:
      'תבלין על האש ולסטייק 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510160',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטרוזיליה 30 גרם',
    description:
      'פטרוזיליה 30 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510170',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תבלין לשווארמה 100 גרם',
    description:
      'תבלין לשווארמה 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510180',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תבלין לפרגיות עוף 100 גרם',
    description:
      'תבלין לפרגיות עוף 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510181',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אבקת שום 120 גרם',
    description:
      'אבקת שום 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510190',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שום גבישי/גרוס 120 גרם',
    description:
      'שום גבישי/גרוס 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510191',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלח לימון 250 גרם',
    description:
      'מלח לימון 250 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510200',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תבלין גריל עוף 120 גרם',
    description:
      'תבלין גריל עוף 120 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510210',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "עלי דפנה 25 גר'",
    description:
      "עלי דפנה 25 גר' מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510220',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל אנגלי שלם 100 גרם',
    description:
      'פלפל אנגלי שלם 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510230',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כוסברה עלים 30 גרם',
    description:
      'כוסברה עלים 30 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510240',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כוסברה טחונה 100 גרם',
    description:
      'כוסברה טחונה 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510241',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כוסבהר שלם (זרעים) 70 גרם',
    description:
      'כוסבהר שלם (זרעים) 70 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510242',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'טימין 50 גרם',
    description: 'טימין 50 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510250',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'רוזמרין 60 גרם',
    description:
      'רוזמרין 60 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510260',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמיר 60 גרם',
    description: 'שמיר 60 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510270',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל מתוק שלם מיובש 150 גרם',
    description:
      'פלפל מתוק שלם מיובש 150 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510280',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל חריף שלם מיובש 150 גרם',
    description:
      'פלפל חריף שלם מיובש 150 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510281',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פלפל סודניה שטה מיובש 50 גרם',
    description:
      'פלפל סודניה שטה מיובש 50 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510282',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שבבי בצל 45 גרם',
    description:
      'שבבי בצל 45 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510290',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תערובת עשבי תיבול לדגים 100 גרם',
    description:
      'תערובת עשבי תיבול לדגים 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510300',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'זנגוויל טחון 100 גרם',
    description:
      'זנגוויל טחון 100 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510310',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פרורי לחם מוזהבים עבים 1 ק"ג',
    description:
      'פרורי לחם מוזהבים עבים 1 ק"ג מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510320',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תיבול שניצל קלאסי 400 גרם',
    description:
      'תיבול שניצל קלאסי 400 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510321',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תיבול שניצל מקסיקני 400 גרם',
    description:
      'תיבול שניצל מקסיקני 400 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510322',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תיבול שניצל בטעם שום 400 גרם',
    description:
      'תיבול שניצל בטעם שום 400 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510323',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אריסה ביתית חריפה 250 גרם',
    description:
      'אריסה ביתית חריפה 250 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510330',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סחוג אדום 170 גרם',
    description:
      'סחוג אדום 170 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510340',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פלפל צ'ומה 180 גרם",
    description:
      "פלפל צ'ומה 180 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים",
    category: 'תבלינים',
    id: '510350',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'עמבה 250 גרם',
    description: 'עמבה 250 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510360',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שומשום 200 גרם',
    description:
      'שומשום 200 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510370',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שומשום מלא 200 גרם',
    description:
      'שומשום מלא 200 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510371',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שומשום שחור 200 גרם',
    description:
      'שומשום שחור 200 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510372',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שום כתוש 250 גרם',
    description:
      'שום כתוש 250 גרם מתוצרת ישראלית איכותית - תבליני בוטיק איכותיים',
    category: 'תבלינים',
    id: '510380',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אמרלנד ריזלינג- יקב תשבי',
    description:
      'אמרלנד ריזלינג 2019 מיקב תשבי בנימינה, \nיין לבן חצי יבש בעל אופי המדגיש סיומת פרחונית וניחוחות פירותיים. האף חושף ריחות מרתקים של מלון ונקטרינה בשלים. \nהיין מומלץ כליווי למאכלי דג, גבינות, סלטים ומנות ראשונות.',
    category: 'יין',
    id: '700010',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פרנץ' ריזלינג- יקב תשבי",
    description:
      "פרנץ' ריזלינג 2019 מיקב תשבי בנימינה\nיין לבן חצי יבש\nיין פירותי ומרענן, ניחן בניחוחות וטעמים של מלון, אננס, אפרסק, תפוח ואשכולית. מתאים להגשה עם ארוחות קלות, מאכלי גבינה ועוף.",
    category: 'יין',
    id: '700020',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מוסקט ויונייה- יקב תשבי',
    description:
      'מוסקט וינייה 2019 מיקב תשבי בנימינה\nיין לבן חצי מתוק \nיין פירותי, טעים ועסיסי עם ניחוחות של מלון, משמש, תפוח עץ ירוק וריח היסמין של המוסקט.',
    category: 'יין',
    id: '700030',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ויונייה גוורצטרמינר- יקב תשבי',
    description:
      'ויונייה גוורצטרמינר 2019 מיקב תשבי בנימינה\nיין לבן חצי יבש\nיין עדין עם ניחוחות של אפרסק לבן, משמש וניחוח הדרים. עדין ונעים בחיך. לשילוב עם מנות דגים בטבון, לחם, שמן זית וזיתים.',
    category: 'יין',
    id: '700040',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כחול לבן- יקב תשבי',
    description:
      'כחול לבן 2018 מיקב תשבי בנימינה\nיין לבן יבש\nיין לבן עדין המובק מבלנד ענבים לבנים. פירותי ובעל ניחוח עשבוני. מתאים כליווי לגבינות, מאפים, פיצות ועופות צלויים בתנור. ',
    category: 'יין',
    id: '700050',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ויונייה- יקב תשבי',
    description:
      'ויונייה 2019 מיקב תשבי בנימינה\nיין פירותי עסיסי ורענן בניחוח קרמבולה, אפרסק ומלון. לצנן לפני ההגשה בימי הקיץ החמים.\nהרכב: 100% ויונייה , מיקום הכרם: הרי יהודה',
    category: 'יין',
    id: '700060',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שיראז- יקב תשבי',
    description:
      'שיראז 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין פירותי, עסיסי וקליל השופע טעמים של שזיפים בשלים, טופי, אוכמניות, פירות יער שחורים ועשבי תיבול. מתאים לשתייה יומיומית ולכל ארוחה בשרית או חלבית. ראוי לצנן כמעט לפני השתייה. אחסון היין במקום חשוך ולח יסייע בהשבחתו.',
    category: 'יין',
    id: '700070',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מרלו- יקב תשבי',
    description:
      'מרלו 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין אדום יבש, צעיר, שופע טעמים פירותיים של אוכמניות, תות שדה וניחוחות תבלין. הוא מאוזן ועגול ויסב הנאה ללוגמים ממנו כבר בהווה. מומלץ ללוות עימו בשרים צלויים בגריל ועוף. איחסון היין במקום חשוך ולח יסיייע בהשבחתו.',
    category: 'יין',
    id: '700080',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קברנה סוביניון- יקב תשבי',
    description:
      'קברנה סוביניון 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין צעיר ופירותי זה נוצר מ- 100% ענבי קברנה סובניון שנבצרו בשיא בשלותם. יין עשיר אך רך ועדין, שיסב הנאה לשותים ממנו כבר כעת. מומלץ ללוות עימו מאכלי בשר אדום ומיני עופות. איחסון היין במקום חשוך ולח יסייע בהשבחתו',
    category: 'יין',
    id: '700090',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קברנה סירה- יקב תשבי',
    description:
      'קברנה סירה 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין צעיר קל ופירותי המביא לידי ביטוי נאה ומאוזן את ענבי הקברנה סובניון וענבי הסירה. היין ניחן בבשומת פירותית בעלת ארומת תותים ועשבי תיבול. מומלץ ללוות עמו ארוחות של מאכלי עוף ופסטה. יש לאחסן את היין בשכיבה במקום חשוך וקריר לשימור איכותו',
    category: 'יין',
    id: '700100',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטיט ורדו- יקב תשבי',
    description:
      'פטיט ורדו 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין צעיר ופירותי, עסיסי ורענן, נוצר מענבי פטיט ורדו, בעל טעמים של דובדבן, פטל, שזיף, עשבי תיבול וליקריץ. מומלץ ללוות עימו בשר מעושן, קישים וגבינות עיזים ארומטיות. איחסון היין במקום חשוך ולח יסייע בהשבחתו',
    category: 'יין',
    id: '700110',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מלברק- יקב תשבי',
    description:
      'מלברק 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין צעיר ופירותי, ניחן בטעמים של חמוציות שחורות, אוכמניות, פטל, פירות יער, מוקה ווניל. יין בעל גוף מלא ועשיר מתאים לבשר ולגבינות בשלות',
    category: 'יין',
    id: '700120',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'אדום סגול- יקב תשבי',
    description:
      'אדום סגול 2019 מיקב תשבי בנימינה\nיין אדום יבש\nיין פירותי, עסיסי וקליל המופק מבלנד ענבים אדומים. שופע טעמים של טופי, אוכמניות, פירות יער שחורים ועשבי תיבול. מתאים לשתייה יומיומית ולכל ארוחה בשרית או חלבית. רצוי לצנן מעט לפני השתייה. אחסון היין במקום חשוך ולח יסייע בהשבחתו',
    category: 'יין',
    id: '700130',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קשיו טבעי- מארז כ320 גרם',
    description: 'קשיו טבעי ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400010',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868258',
    snHerzelia: '61782',
  },
  {
    name: 'פקאן טבעי מקולף- מארז כ300 גרם',
    description: 'פקאן טבעי מקולף- מארז כ300 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400020',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868259',
    snHerzelia: '60575',
  },
  {
    name: 'אגוזי מלך טבעיים- מארז כ240 גרם',
    description: 'אגוזי מלך טבעיים- מארז כ240 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400030',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868260',
    snHerzelia: '60032',
  },
  {
    name: 'שקד אמריקאי מקולף- מארז כ300 גרם',
    description: 'שקד אמריקאי מקולף- מארז כ300 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400040',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868261',
    snHerzelia: '62050',
  },
  {
    name: 'שקד טבעי פרוס- מארז כ230 גרם',
    description: 'שקד טבעי פרוס- מארז כ230 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400041',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868262',
    snHerzelia: '61734',
  },
  {
    name: 'שקד טבעי קצוץ גפרורים- מארז כ250 גרם',
    description: 'שקד טבעי קצוץ גפרורים- מארז כ250 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400042',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868263',
    snHerzelia: '61721',
  },
  {
    name: 'בוטנים טבעיים מקלופים- מארז כ300 גרם',
    description: 'בוטנים טבעיים מקלופים- מארז כ300 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400050',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868264',
    snHerzelia: '61705',
  },
  {
    name: 'אגוזי מקדמיה טבעיים- מארז כ340 גרם',
    description: 'אגוזי מקדמיה טבעיים- מארז כ340 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400060',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868265',
    snHerzelia: '64148',
  },
  {
    name: 'פיסטיק חלבי טבעי מקולף- מארז כ250 גרם',
    description: 'פיסטיק חלבי טבעי מקולף- מארז כ250 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400070',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868266',
    snHerzelia: '60284',
  },
  {
    name: 'אגוז ברזיל טבעי מקולף- מארז כ320 גרם',
    description: 'אגוז ברזיל טבעי מקולף- מארז כ320 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400080',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868267',
    snHerzelia: '60978',
  },
  {
    name: 'אגוזי לוז טבעיים קלופים- מארז כ250 גרם',
    description: 'אגוזי לוז טבעיים קלופים- מארז כ250 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400090',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868268',
    snHerzelia: '62555',
  },
  {
    name: 'קוקוס טבעי מיובש רצועות- מארז כ250 גרם',
    description: 'קוקוס טבעי מיובש רצועות- מארז כ250 גרם ללא תוספות, לא קלוי',
    category: 'אגוזים',
    id: '400100',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868269',
    snHerzelia: '64666',
  },
  {
    name: 'משמש טבעי מיובש- מארז כ400 גרם',
    description: 'משמש טבעי מיובש- מארז כ400 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400110',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868270',
    snHerzelia: '61388',
  },
  {
    name: 'תאנה טבעית מיובשת- מארז כ300 גרם',
    description: 'תאנה טבעית מיובשת- מארז כ300 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400120',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868271',
    snHerzelia: '61850',
  },
  {
    name: "גוג'י ברי טבעי מיובש- מארז כ250 גרם",
    description: "גוג'י ברי טבעי מיובש- מארז כ250 גרם ללא תוספות- סופר פוד",
    category: 'פירות יבשים טבעיים',
    id: '400130',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868272',
    snHerzelia: '62087',
  },
  {
    name: 'חמוציות מיובשות- מארז כ300 גרם',
    description: 'חמוציות מיובשות- מארז כ300 גרם ברכז תפוחים ללא תוספת סוכר',
    category: 'פירות יבשים טבעיים',
    id: '400140',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868273',
    snHerzelia: '61982',
  },
  {
    name: 'אננס טבעי מיובש- מארז כ250 גרם',
    description: 'אננס טבעי מיובש- מארז כ250 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400150',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868274',
    snHerzelia: '65864',
  },
  {
    name: 'מנגו טבעי מיובש- מארז כ250 גרם',
    description: 'מנגו טבעי מיובש- מארז כ250 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400160',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868275',
    snHerzelia: '62203',
  },
  {
    name: 'דובדבנים טבעיים מיובשים- מארז כ350 גרם',
    description: 'דובדבנים טבעיים מיובשים- מארז כ350 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400170',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868276',
    snHerzelia: '60131',
  },
  {
    name: 'אוכמניות טבעי מיובש- מארז כ300 גרם',
    description: 'אוכמניות טבעי מיובש- מארז כ300 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400180',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868277',
    snHerzelia: '60134',
  },
  {
    name: 'גרעיני דלעת מקולפים ומיובשים- מארז כ280 גרם',
    description: 'גרעיני דלעת מקולפים ומיובשים- מארז כ280 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400190',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868278',
    snHerzelia: '60390',
  },
  {
    name: 'שזיף טבעי ללא גלעין ומיובש- מארז כ450 גרם',
    description: 'שזיף טבעי ללא גלעין ומיובש- מארז כ450 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400200',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868279',
    snHerzelia: '61813',
  },
  {
    name: 'צימוק כהה גדול- מארז כ400 גרם',
    description: 'צימוק כהה גדול- מארז כ400 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400210',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868280',
    snHerzelia: '61115',
  },
  {
    name: 'צימוק בהיר גדול- מארז כ400 גרם',
    description: 'צימוק בהיר גדול- מארז כ400 גרם ללא תוספות',
    category: 'פירות יבשים טבעיים',
    id: '400211',
    saleType: 'WIEGHT_PACK',
    snWebSite: '2868281',
    snHerzelia: '61825',
  },
  {
    name: 'צנובר- מארז כ250 גרם',
    description: 'צנובר- מארז כ250 גרם לא קלוי וללא תוספות',
    category: 'אגוזים',
    id: '400220',
    saleType: 'WIEGHT_PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטים סיניים אורגני',
    description: 'נבטים סיניים אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600010',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי צנונית אורגני',
    description: 'נבטי צנונית אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600011',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי חמניה אורגני',
    description: 'נבטי חמניה אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600012',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי ברוקולי אורגני',
    description: 'נבטי ברוקולי אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600013',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי אלפלפא',
    description: 'נבטי אלפלפא מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600014',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי אפונה',
    description: 'נבטי אפונה מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600015',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי קייל',
    description: 'נבטי קייל מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600016',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נבטי כרישה אורגני',
    description: 'נבטי כרישה אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600017',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מיקס נבטים אורגני',
    description: 'מיקס נבטים אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600018',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מיקס נבטים ענק אורגני',
    description: 'מיקס נבטים ענק אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600019',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מאש מונבט',
    description: 'מאש מונבט מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: 600110,
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חומוס מונבט',
    description: 'חומוס מונבט מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: 600111,
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטריות  שיטאקי אורגניות',
    description: 'פטריות  שיטאקי אורגניות מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600020',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: "פטריות ארינג'י אורגניות",
    description: "פטריות ארינג'י אורגניות מתוצרת ישראלית איכותית",
    category: 'אורגני',
    id: '600021',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטריות יער אורגניות',
    description: 'פטריות יער אורגניות מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600022',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'תרד אורגני',
    description: 'תרד אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600030',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מיקס עלי בייבי אורגניים',
    description: 'מיקס עלי בייבי אורגניים מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600040',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קייל אורגני כרוב על',
    description: 'קייל אורגני כרוב על מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600050',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטרוזילה אורגני',
    description: 'פטרוזילה אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600060',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'כוסברה אורגני',
    description: 'כוסברה אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600070',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בזיליקום אורגני',
    description: 'בזיליקום אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600080',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'שמיר אורגני',
    description: 'שמיר אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600090',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'נענע אורגני',
    description: 'נענע אורגני מתוצרת ישראלית איכותית',
    category: 'אורגני',
    id: '600100',
    saleType: 'PACK',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גאודה',
    description: "גאודה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520010',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גאודה חרדל',
    description: "גאודה חרדל 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520011',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גאודה כמון',
    description: "גאודה כמון 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520012',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גאודה עשבי תיבול',
    description: "גאודה עשבי תיבול 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520013',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מוצרלה',
    description: "מוצרלה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520020',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בייבי מוצרלה',
    description: "בייבי מוצרלה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520021',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מוצרלה מגורדת',
    description: "מוצרלה מגורדת 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520022',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'בוראטה- מוצרלה במילוי שמנת כפרית',
    description:
      "בוראטה- מוצרלה במילוי שמנת כפרית 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520023',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גבינת שמנת בטעם טבעי',
    description: "גבינת שמנת בטעם טבעי 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520030',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גבינת שמנת עם זיתים',
    description: "גבינת שמנת עם זיתים 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520031',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גבינת שמנת עם שום שמיר',
    description: "גבינת שמנת עם שום שמיר 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520032',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גרוייר',
    description: "גרוייר 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520040',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'מנצגו',
    description: "מנצגו 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520050',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'עומר',
    description: "עומר 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520060',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קפרינו',
    description: "קפרינו 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520070',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קצוטה',
    description: "קצוטה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520080',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קשקבל',
    description: "קשקבל 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520090',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'רוקפור',
    description: "רוקפור 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520100',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קממברט בקר',
    description: "קממברט בקר 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520110',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קממברט עיזים',
    description: "קממברט עיזים 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520111',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'חלומי',
    description: "חלומי 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520120',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'יוגורט כבשים BIO',
    description: "יוגורט כבשים BIO 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520130',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'יוגורט עזים BIO',
    description: "יוגורט עזים BIO 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520131',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'לאבנה עיזים',
    description: "לאבנה עיזים 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520140',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'סנט מור',
    description: "סנט מור 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520150',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'עז מה גבינה מחלב עזים למריחה',
    description:
      "עז מה גבינה מחלב עזים למריחה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520160',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'פטה כבשים',
    description: "פטה כבשים 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520170',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'קרם פרש',
    description: "קרם פרש 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520180',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'ריקוטה',
    description: "ריקוטה 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520190',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
  {
    name: 'גלילית',
    description: "גלילית 'משק יעקבס' מתוצרת ישראלית איכותית",
    category: 'גבינות',
    id: '520200',
    saleType: 'UNIT',
    snWebSite: '',
    snHerzelia: '',
  },
]
